"""
GMN-Football-3 — Checkpoint Contract & Metadata Validation System (Python)
Authoritative verification of checkpoint compatibility, observation/action schemas,
role-slice non-zero validation, and experiment manifest serialization.
"""

import os

# --- AUTOGENERATED CONTRACT CONSTANTS (DO NOT EDIT DIRECTLY) ---
# Generated from src/engine/Contract.ts by scripts/sync_contracts.ts
GMN_ENV_VERSION = "3.1.0"
OBSERVATION_SCHEMA_VERSION = "simple115_v3_role"
ACTION_SCHEMA_VERSION = "discrete19_v1"

ROLE_VOCABULARY = ["GK", "CB", "LB", "RB", "CDM", "CM", "LM", "RM", "LW", "RW", "CAM", "ST"]
ROLE_DIM = 12
BASE_OBSERVATION_DIM = 115
OBSERVATION_DIM = 127
ACTION_SPACE_SIZE = 19

EVENT_CODE_MAP = [
    None,
    "goal",
    "shot",
    "shot_saved",
    "shot_missed",
    "pass",
    "interception",
    "tackle",
    "foul",
    "kickoff",
    "out_of_bounds",
    "scenario_complete",
    "scenario_failed",
    "offside",
    "pass_completed",
    "pass_intercepted",
    "shot_blocked",
]
# --- END AUTOGENERATED CONTRACT CONSTANTS ---
import json
import hashlib
import datetime
from typing import Dict, Any, Optional, Tuple

GMN_ENV_VERSION = "3.1.0"
OBSERVATION_SCHEMA_VERSION = "simple115_v3_role"
BASE_OBSERVATION_DIM = 115
ROLE_DIM = 12
OBSERVATION_DIM = 127
ACTION_SCHEMA_VERSION = "discrete19_v1"
ACTION_SPACE_SIZE = 19
POLICY_ARCHITECTURE_SCHEMA_VERSION = "policy_architecture_v1"
GNN_GRAPH_SCHEMA_ID = "gnn_graph_schema_v3.json"
GNN_NODE_FEATURE_DIM = 32
GNN_EDGE_FEATURE_DIM = 10
GNN_CONTEXT_DIM = 8


def create_policy_checkpoint_contract(policy_architecture: str = "flat") -> Dict[str, Any]:
    """Return versioned architecture metadata stored with MAPPO checkpoints."""
    contract: Dict[str, Any] = {
        "policy_architecture_schema": POLICY_ARCHITECTURE_SCHEMA_VERSION,
        "policy_architecture": policy_architecture,
        "env_version": GMN_ENV_VERSION,
        "observation_schema": OBSERVATION_SCHEMA_VERSION,
        "observation_dim": OBSERVATION_DIM,
        "action_schema": ACTION_SCHEMA_VERSION,
        "action_space_size": ACTION_SPACE_SIZE,
    }
    if policy_architecture.startswith("gnn:"):
        contract.update({
            "graph_schema": GNN_GRAPH_SCHEMA_ID,
            "node_feature_dim": GNN_NODE_FEATURE_DIM,
            "edge_feature_dim": GNN_EDGE_FEATURE_DIM,
            "graph_context_dim": GNN_CONTEXT_DIM,
        })
    return contract


def validate_policy_checkpoint(
    checkpoint: Dict[str, Any],
    expected_architecture: Optional[str] = None,
) -> Tuple[bool, Optional[str]]:
    """Validate flat legacy or versioned GNN MAPPO checkpoints.

    Legacy checkpoints without architecture metadata are interpreted as flat
    MAPPO. GNN checkpoints must carry the full graph/model contract so a graph
    tensor or encoder change cannot silently load into the wrong architecture.
    """
    architecture = checkpoint.get("policy_architecture", "flat")
    if expected_architecture is not None and architecture != expected_architecture:
        return False, (
            f"Policy architecture mismatch: expected {expected_architecture!r}, "
            f"got {architecture!r}."
        )
    if architecture != "flat" and architecture not in (
        "gnn:gat", "gnn:geometry", "gnn:mlp"
    ):
        return False, f"Unsupported policy architecture: {architecture!r}."

    if int(checkpoint.get("obs_dim", OBSERVATION_DIM)) != OBSERVATION_DIM:
        return False, f"Observation dimension mismatch: expected {OBSERVATION_DIM}."
    if int(checkpoint.get("action_dim", ACTION_SPACE_SIZE)) != ACTION_SPACE_SIZE:
        return False, f"Action dimension mismatch: expected {ACTION_SPACE_SIZE}."

    actor_state = checkpoint.get("actor")
    if not isinstance(actor_state, dict):
        return False, "Checkpoint is missing an actor state dictionary."

    if architecture == "flat":
        contract = checkpoint.get("checkpoint_contract")
        if contract is not None:
            valid, reason = validate_checkpoint_metadata(contract)
            if not valid:
                return False, reason
            expected_contract = create_policy_checkpoint_contract("flat")
            for key, expected in expected_contract.items():
                if contract.get(key) != expected:
                    return False, f"Flat checkpoint contract mismatch for {key}."
        first_layer = actor_state.get("net.0.weight")
        if first_layer is None or tuple(first_layer.shape)[1] != OBSERVATION_DIM:
            return False, "Flat actor first layer does not match the 127-dim observation contract."
        return True, None

    contract = checkpoint.get("checkpoint_contract")
    if not isinstance(contract, dict):
        return False, "GNN checkpoint is missing checkpoint_contract metadata."
    valid, reason = validate_checkpoint_metadata(contract)
    if not valid:
        return False, reason
    expected_contract = create_policy_checkpoint_contract(architecture)
    for key, expected in expected_contract.items():
        if contract.get(key) != expected:
            return False, (
                f"GNN checkpoint contract mismatch for {key}: "
                f"expected {expected!r}, got {contract.get(key)!r}."
            )

    encoder_prefix = {
        "gnn:gat": "encoder.input_proj.weight",
        "gnn:geometry": "encoder.feature_mlp.0.weight",
        "gnn:mlp": "encoder.node_encoder.0.weight",
    }[architecture]
    if encoder_prefix not in actor_state:
        return False, f"Actor state does not contain the {architecture} encoder signature."
    policy_head = actor_state.get("policy_head.weight")
    if policy_head is None or tuple(policy_head.shape)[0] != ACTION_SPACE_SIZE:
        return False, "GNN actor policy head does not match the discrete19 action contract."
    critic_state = checkpoint.get("critic")
    if critic_state is not None:
        if not isinstance(critic_state, dict) or encoder_prefix not in critic_state:
            return False, f"Critic state does not contain the {architecture} encoder signature."
        value_head = critic_state.get("value_head.2.weight")
        if value_head is None or tuple(value_head.shape)[0] != 1:
            return False, "GNN critic value head must produce one scalar value."
    return True, None


def load_mappo_actor(checkpoint: Dict[str, Any], expected_architecture: Optional[str] = None):
    """Validate and construct a flat or GNN MAPPO actor from a checkpoint."""
    valid, reason = validate_policy_checkpoint(checkpoint, expected_architecture)
    if not valid:
        raise ValueError(f"Invalid MAPPO checkpoint: {reason}")
    architecture = checkpoint.get("policy_architecture", "flat")
    if architecture == "flat":
        from training.mappo_networks import SharedActor
        actor = SharedActor(
            obs_dim=int(checkpoint.get("obs_dim", OBSERVATION_DIM)),
            action_dim=int(checkpoint.get("action_dim", ACTION_SPACE_SIZE)),
            hidden=64,
        )
    else:
        from training.gnn_mappo_networks import GNNMAPPOActor
        actor = GNNMAPPOActor(
            action_dim=int(checkpoint.get("action_dim", ACTION_SPACE_SIZE)),
            encoder_type=architecture.split(":", 1)[1],
        )
    actor.load_state_dict(checkpoint["actor"])
    return actor


def load_mappo_critic(checkpoint: Dict[str, Any]):
    """Construct the architecture-matched critic when present in a checkpoint."""
    valid, reason = validate_policy_checkpoint(checkpoint)
    if not valid:
        raise ValueError(f"Invalid MAPPO checkpoint: {reason}")
    if "critic" not in checkpoint:
        return None
    architecture = checkpoint.get("policy_architecture", "flat")
    if architecture == "flat":
        from training.mappo_networks import CentralizedCritic
        critic = CentralizedCritic(
            obs_dim=int(checkpoint.get("obs_dim", OBSERVATION_DIM)), hidden=64
        )
    else:
        from training.gnn_mappo_networks import GNNMAPPOCritic
        critic = GNNMAPPOCritic(encoder_type=architecture.split(":", 1)[1])
    critic.load_state_dict(checkpoint["critic"])
    return critic


def compute_file_sha256(file_path: str) -> str:
    """Computes SHA256 hex digest of a checkpoint file."""
    if not os.path.exists(file_path):
        return "FILE_NOT_FOUND"
    sha = hashlib.sha256()
    with open(file_path, "rb") as f:
        while chunk := f.read(8192):
            sha.update(chunk)
    return sha.hexdigest()


def validate_checkpoint_weights(actor_state_dict: Dict[str, Any]) -> Tuple[bool, bool, Optional[str]]:
    """
    Validates PyTorch actor state dict against the authoritative 127-dim contract.
    Returns: (is_valid, is_role_aware, rejection_reason)
    """
    # Find layer 0 weight
    w0_key = None
    for k in ["0.weight", "fc1.weight", "actor.0.weight", "policy.0.weight"]:
        if k in actor_state_dict:
            w0_key = k
            break

    if w0_key is None:
        # Check first key ending in weight
        for k in actor_state_dict.keys():
            if "weight" in k:
                w0_key = k
                break

    if w0_key is None:
        return False, False, "Could not locate first linear layer weight in actor state dict."

    w0 = actor_state_dict[w0_key]
    # Expect w0 shape: (hidden_dim, in_dim) e.g. (64, 127)
    if hasattr(w0, "shape"):
        hidden_dim, in_dim = w0.shape[0], w0.shape[1]
    elif hasattr(w0, "__len__") and hasattr(w0[0], "__len__"):
        hidden_dim, in_dim = len(w0), len(w0[0])
    else:
        return False, False, "Invalid w0 tensor shape or type."

    if in_dim != OBSERVATION_DIM:
        return (
            False,
            False,
            f"Input dimension mismatch: expected {OBSERVATION_DIM} ({OBSERVATION_SCHEMA_VERSION}), got {in_dim}.",
        )

    # Check role slice (BASE_OBSERVATION_DIM .. OBSERVATION_DIM - 1)
    non_zero_role_weights = 0
    total_role_weights = 0

    if hasattr(w0, "cpu"):
        w0_np = w0.detach().cpu().numpy()
    else:
        import numpy as np
        w0_np = np.array(w0)

    role_slice = w0_np[:, BASE_OBSERVATION_DIM:OBSERVATION_DIM]
    total_role_weights = role_slice.size
    non_zero_role_weights = int((abs(role_slice) > 1e-7).sum())

    if non_zero_role_weights == 0:
        return (
            False,
            False,
            f"CHECKPOINT REJECTED: All {total_role_weights} role-feature weights (indices {BASE_OBSERVATION_DIM}..{OBSERVATION_DIM-1}) are exact zeros. This indicates a zero-padded placeholder/smoke-test checkpoint rather than a policy genuinely trained with role features.",
        )

    return True, True, None


def validate_checkpoint_metadata(meta: Dict[str, Any]) -> Tuple[bool, Optional[str]]:
    """Validates metadata dictionary."""
    if meta.get("env_version") != GMN_ENV_VERSION:
        return False, f"Environment version mismatch: expected {GMN_ENV_VERSION}, got {meta.get('env_version')}."
    if meta.get("observation_schema") != OBSERVATION_SCHEMA_VERSION or meta.get("observation_dim") != OBSERVATION_DIM:
        return (
            False,
            f"Observation schema mismatch: expected {OBSERVATION_SCHEMA_VERSION} ({OBSERVATION_DIM}-dim), got {meta.get('observation_schema')} ({meta.get('observation_dim')}-dim).",
        )
    if meta.get("action_schema") != ACTION_SCHEMA_VERSION or meta.get("action_space_size") != ACTION_SPACE_SIZE:
        return (
            False,
            f"Action schema mismatch: expected {ACTION_SCHEMA_VERSION} ({ACTION_SPACE_SIZE} actions), got {meta.get('action_schema')} ({meta.get('action_space_size')} actions).",
        )
    return True, None


def create_experiment_manifest(
    algorithm: str,
    scenario: str,
    training_steps: int,
    seed: int,
    checkpoint_path: str,
    actor_state_dict: Optional[Dict[str, Any]] = None,
    hyperparameters: Optional[Dict[str, Any]] = None,
    git_commit: Optional[str] = None
) -> Dict[str, Any]:
    """Generates a standardized experiment manifest dictionary."""
    chk_hash = compute_file_sha256(checkpoint_path)
    is_valid = True
    is_role_aware = False
    rejection_reason = None

    if actor_state_dict is not None:
        is_valid, is_role_aware, rejection_reason = validate_checkpoint_weights(actor_state_dict)
    elif algorithm in ["rule_based", "scripted", "random", "noop"]:
        is_valid = True
        is_role_aware = True

    manifest = {
        "algorithm": algorithm.lower(),
        "scenario": scenario,
        "training_steps": training_steps,
        "seed": seed,
        "env_version": GMN_ENV_VERSION,
        "observation_schema": OBSERVATION_SCHEMA_VERSION,
        "observation_dim": OBSERVATION_DIM,
        "action_schema": ACTION_SCHEMA_VERSION,
        "action_space_size": ACTION_SPACE_SIZE,
        "git_commit": git_commit or "unavailable",
        "checkpoint_path": checkpoint_path,
        "checkpoint_hash": chk_hash,
        "is_role_aware": is_role_aware,
        "role_weights_non_zero": is_role_aware,
        "is_valid": is_valid,
        "rejection_reason": rejection_reason,
        "hyperparameters": hyperparameters or {},
        "created_at": datetime.datetime.now(datetime.timezone.utc).isoformat().replace("+00:00", "Z"),
    }
    return manifest
