"""
GMN-Football-3 — PettingZoo Multi-Agent Parallel Environment Wrapper
Authoritative Environment Binding for Multi-Agent Football Simulation.

Wraps the GMN-Football-3 WebSocket bridge server as a PettingZoo ParallelEnv.
Supports simultaneous control of N left-team players with independent per-agent
observations (Box(115,)) and discrete action spaces (Discrete(19)).

NOTE: Connection/lifecycle helper methods are duplicated here from gmn_gym.py
as a deliberate isolation boundary to avoid touching verified single-agent code.
(Known follow-up cleanup opportunity: extract shared transport/lifecycle helpers).
"""

import os
import sys
import time
import json
import struct
import subprocess
from typing import Dict, List, Optional, Tuple, Any

import numpy as np
import requests
import websockets.sync.client
from gymnasium import spaces
from pettingzoo.utils.env import ParallelEnv


def _npx_cmd():
    return ["npx.cmd"] if sys.platform == "win32" else ["npx"]


# --- AUTOGENERATED CONTRACT CONSTANTS (DO NOT EDIT DIRECTLY) ---
# Generated from src/engine/Contract.ts by scripts/sync_contracts.ts
GMN_ENV_VERSION = "3.1.0"
OBSERVATION_SCHEMA_VERSION = "simple115_v3_role"
ACTION_SCHEMA_VERSION = "discrete19_v1"

ROLE_VOCABULARY = ["GK", "CB", "LB", "RB", "CDM", "CM", "LM", "RM", "LW", "RW", "CAM", "ST"]
ROLE_DIM = 12
BASE_OBSERVATION_DIM = 115
OBSERVATION_DIM = 127
ACTION_SPACE_SIZE = 19

EVENT_CODE_MAP = [
    None,
    "goal",
    "shot",
    "shot_saved",
    "shot_missed",
    "pass",
    "interception",
    "tackle",
    "foul",
    "kickoff",
    "out_of_bounds",
    "scenario_complete",
    "scenario_failed",
    "offside",
]
# --- END AUTOGENERATED CONTRACT CONSTANTS ---


class CooperativeRewardShaper:
    """
    Shapes agent rewards in GMN-Football-3 to encourage multi-agent passing
    and penalize unassisted direct shooting / excessive dribbling.
    """

    def __init__(
        self,
        reward_pass_completion: float = 0.25,
        reward_assisted_goal_bonus: float = 0.50,
        penalty_solitary_shot: float = -0.30,
        penalty_ball_hogging: float = -0.005,
        max_unassisted_hold_ticks: int = 30,
    ):
        self.r_pass = reward_pass_completion
        self.r_assisted_goal = reward_assisted_goal_bonus
        self.p_solitary_shot = penalty_solitary_shot
        self.p_ball_hogging = penalty_ball_hogging
        self.max_hold_ticks = max_unassisted_hold_ticks
        self.reset()

    def reset(self) -> None:
        """Reset sequence trackers at the start of an episode."""
        self.pass_chain_length: int = 0
        self.current_holder_id: Optional[str] = None
        self.holder_ticks: int = 0

    def compute_shaped_rewards(
        self,
        base_rewards: Dict[str, float],
        step_events: List[Dict[str, Any]],
        info_ground_truth: Dict[str, Any],
        active_agents: List[str],
    ) -> Dict[str, float]:
        """
        Calculates shaped rewards for all active left-team agents.
        """
        shaped_rewards = {agent_id: base_rewards.get(agent_id, 0.0) for agent_id in active_agents}

        # 1. Track Possession & Apply Ball-Hogging Penalties
        ball_owner = info_ground_truth.get("current_ball_owner") if info_ground_truth else None
        if isinstance(ball_owner, dict) and ball_owner.get("team") == "left":
            holder_id = ball_owner.get("agent_id")
            if holder_id and holder_id == self.current_holder_id:
                self.holder_ticks += 1
            else:
                self.current_holder_id = holder_id
                self.holder_ticks = 1

            if self.holder_ticks > self.max_hold_ticks and holder_id in shaped_rewards:
                shaped_rewards[holder_id] += self.p_ball_hogging
        else:
            self.current_holder_id = None
            self.holder_ticks = 0

        # 2. Process Discrete Engine Events
        for event in step_events:
            if not isinstance(event, dict):
                continue
            event_type = event.get("type")
            event_team = event.get("team")
            agent_id = event.get("agent_id")

            if event_team != "left":
                continue

            if event_type == "PASS_COMPLETED":
                self.pass_chain_length += 1
                if agent_id in shaped_rewards:
                    shaped_rewards[agent_id] += self.r_pass

            elif event_type in ("PASS_FAILED", "TURNOVER_CONCEDED"):
                self.pass_chain_length = 0

            elif event_type == "SHOT_TAKEN":
                if self.pass_chain_length == 0 and agent_id in shaped_rewards:
                    shaped_rewards[agent_id] += self.p_solitary_shot

            elif event_type == "GOAL_SCORED":
                if self.pass_chain_length > 0:
                    for aid in shaped_rewards:
                        shaped_rewards[aid] += self.r_assisted_goal
                self.pass_chain_length = 0

        return shaped_rewards


# --- AUTOGENERATED CONTRACT CONSTANTS (DO NOT EDIT DIRECTLY) ---
# Generated from src/engine/Contract.ts by scripts/sync_contracts.ts
GMN_ENV_VERSION = "3.1.0"
OBSERVATION_SCHEMA_VERSION = "simple115_v3_role"
ACTION_SCHEMA_VERSION = "discrete19_v1"

ROLE_VOCABULARY = ["GK", "CB", "LB", "RB", "CDM", "CM", "LM", "RM", "LW", "RW", "CAM", "ST"]
ROLE_DIM = 12
BASE_OBSERVATION_DIM = 115
OBSERVATION_DIM = 127
ACTION_SPACE_SIZE = 19

EVENT_CODE_MAP = [
    None,
    "goal",
    "shot",
    "shot_saved",
    "shot_missed",
    "pass",
    "interception",
    "tackle",
    "foul",
    "kickoff",
    "out_of_bounds",
    "scenario_complete",
    "scenario_failed",
    "offside",
]
# --- END AUTOGENERATED CONTRACT CONSTANTS ---


class GMNMultiAgentEnv(ParallelEnv):
    """
    PettingZoo ParallelEnv wrapper for GMN-Football-3 multi-agent scenarios.
    Controls N players on the left team simultaneously.
    """

    metadata = {
        "render_modes": ["human", "rgb_array"],
        "name": "gmn_football_multiagent_v3",
    }

    def __init__(
        self,
        scenario: str = "academy_3_vs_1_with_keeper",
        host: str = "127.0.0.1",
        port: Optional[int] = None,
        auto_start_bridge: bool = True,
        render_mode: Optional[str] = None,
        enable_reward_shaping: bool = True,
    ):
        super().__init__()
        self.scenario = scenario
        self.host = host
        self.port = port or int(os.environ.get("GMN_BRIDGE_PORT", "5050"))
        self.base_url = f"http://{self.host}:{self.port}"
        self.ws_url = f"ws://{self.host}:{self.port}"
        self.auto_start_bridge = auto_start_bridge
        self.render_mode = render_mode
        self.enable_reward_shaping = enable_reward_shaping
        self.bridge_process: Optional[subprocess.Popen] = None
        self.ws_client = None
        self.reward_shaper = CooperativeRewardShaper() if enable_reward_shaping else None

        self._step_count = 0
        self.agents: List[str] = []
        self.possible_agents: List[str] = []

        # Observation and action spaces (identical across all agents)
        self._obs_space = spaces.Box(
            low=-100.0,
            high=100.0,
            shape=(OBSERVATION_DIM,),
            dtype=np.float32,
        )
        self._act_space = spaces.Discrete(ACTION_SPACE_SIZE)

        # Ensure Bridge Server is running & connected
        self._ensure_bridge_running()
        # P0 #6: bounded WS receive timeout (never hang on a missing frame).
        self.ws_recv_timeout = float(os.environ.get("GMN_WS_RECV_TIMEOUT", "10.0"))
        self._connect_ws()

        # Perform initial reset to discover controllable agents
        self.reset()

    def _ensure_bridge_running(self):
        """Verifies connection to bridge server or starts it via npx tsx."""
        for attempt in range(6):
            try:
                res = requests.get(f"{self.base_url}/health", timeout=1.0)
                if res.status_code == 200:
                    info = res.json()
                    bridge_obs_dim = info.get("observation_dim", 115)
                    bridge_act_dim = info.get("action_space_size", info.get("action_dim", 19))
                    if bridge_obs_dim != OBSERVATION_DIM or bridge_act_dim != ACTION_SPACE_SIZE:
                        raise RuntimeError(
                            f"[GMN-PettingZoo Contract Mismatch] Bridge reports obs_dim={bridge_obs_dim}, "
                            f"act_dim={bridge_act_dim}; Expected obs_dim={OBSERVATION_DIM}, act_dim={ACTION_SPACE_SIZE}."
                        )
                    return
            except requests.RequestException:
                pass

            if self.auto_start_bridge and self.bridge_process is None:
                print(f"[GMN-PettingZoo] Launching Headless Bridge Server on {self.base_url}...")
                bridge_script = os.path.join(os.path.dirname(__file__), "bridge_server.ts")
                self.bridge_process = subprocess.Popen(
                    _npx_cmd() + ["tsx", bridge_script],
                    env=dict(os.environ, GMN_BRIDGE_PORT=str(self.port)),
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                time.sleep(2.0)
            else:
                time.sleep(1.0)

    def _connect_ws(self):
        """Establishes or reconnects WebSocket client connection."""
        if self.ws_client is not None:
            try:
                self.ws_client.close()
            except Exception:
                pass
        self.ws_client = websockets.sync.client.connect(
            self.ws_url, max_size=None, ping_interval=None, open_timeout=5.0
        )

    def _recv_frame(self, operation: str):
        """
        P0 #6: Receive one WebSocket frame with a bounded timeout. Raises a
        clear RuntimeError (with operation context) on timeout instead of
        blocking forever. No automatic retries (a retried step could duplicate
        an environment transition).
        """
        if self.ws_client is None:
            raise RuntimeError(f"[GMN-PettingZoo WS Error] No WebSocket connection during '{operation}'.")
        try:
            return self.ws_client.recv(timeout=self.ws_recv_timeout)
        except TimeoutError:
            raise RuntimeError(
                f"[GMN-PettingZoo WS Timeout] No frame received within {self.ws_recv_timeout}s "
                f"during '{operation}'. The bridge server is unresponsive."
            ) from None
        except RuntimeError as e:
            if "timed out" in str(e).lower():
                raise RuntimeError(
                    f"[GMN-PettingZoo WS Timeout] No frame received within {self.ws_recv_timeout}s "
                    f"during '{operation}'. The bridge server is unresponsive."
                ) from None
            raise RuntimeError(f"[GMN-PettingZoo WS Error] during '{operation}': {e}") from e
        except Exception as e:
            raise RuntimeError(f"[GMN-PettingZoo WS Error] during '{operation}': {e}") from e

    def observation_space(self, agent: str) -> spaces.Space:
        """Returns the observation space for the given agent."""
        return self._obs_space

    def action_space(self, agent: str) -> spaces.Space:
        """Returns the action space for the given agent."""
        return self._act_space

    def _recv_reset_response(self) -> Dict[str, Any]:
        """Receive a reset response, skipping unsolicited broadcast frames ON the shared WS.

        P1 #13: structural validation — a valid reset response must contain
        'observation' or 'observations' with the correct OBSERVATION_DIM shape.
        """
        for _ in range(60):
            frame = self._recv_frame("reset")
            if isinstance(frame, str):
                try:
                    candidate = json.loads(frame)
                except json.JSONDecodeError:
                    continue
                if self._is_valid_reset_response(candidate):
                    return candidate
            # unsolicited broadcast / malformed frame — skip
        raise RuntimeError("[GMN-PettingZoo] No structurally valid reset response received (only broadcast frames)")

    @staticmethod
    def _is_valid_reset_response(candidate: Any) -> bool:
        """P1 #13: structural validation of a reset response payload."""
        if not isinstance(candidate, dict):
            return False
        obs = candidate.get("observation")
        if isinstance(obs, (list, tuple)) and len(obs) == OBSERVATION_DIM:
            return True
        observations = candidate.get("observations")
        if (
            isinstance(observations, (list, tuple))
            and len(observations) > 0
            and all(isinstance(o, (list, tuple)) and len(o) == OBSERVATION_DIM for o in observations)
        ):
            return True
        return False

    def _recv_step_response(self, num_agents: int) -> Tuple[bytes, Optional[Dict[str, Any]]]:
        """Receive a binary step response, skipping unsolicited broadcast frames ON the shared WS.
        
        Also collects any EPISODE_STATS JSON frames that arrive alongside the binary response.
        """
        obs_bytes = OBSERVATION_DIM * 4
        expected_len = 17 + obs_bytes * num_agents
        episode_stats: Optional[Dict[str, Any]] = None
        for _ in range(60):
            data = self._recv_frame("step")
            if isinstance(data, (bytes, bytearray)) and len(data) == expected_len:
                return bytes(data), episode_stats
            # Collect EPISODE_STATS JSON frames
            if isinstance(data, str):
                try:
                    parsed = json.loads(data)
                    if isinstance(parsed, dict) and parsed.get("type") == "EPISODE_STATS":
                        episode_stats = parsed
                        continue
                except (json.JSONDecodeError, AttributeError):
                    pass
            # unsolicited broadcast (training_status/telemetry) — skip
        raise RuntimeError(
            f"[GMN-PettingZoo Frame Length Error] Expected {expected_len} bytes, got only broadcast frames"
        )

    def reset(
        self,
        seed: Optional[int] = None,
        options: Optional[Dict[str, Any]] = None,
    ) -> Tuple[Dict[str, np.ndarray], Dict[str, Any]]:
        """
        Resets the multi-agent environment and returns per-agent initial observations.
        """
        if getattr(self, "_needs_bridge", False):
            self._ensure_bridge_running()
            self._connect_ws()
            self._needs_bridge = False

        self._step_count = 0
        if self.reward_shaper is not None:
            self.reward_shaper.reset()

        target_scenario = self.scenario
        if options and "scenario" in options:
            target_scenario = options["scenario"]

        payload: Dict[str, Any] = {
            "type": "reset",
            "scenario": target_scenario,
        }
        if seed is not None:
            payload["seed"] = int(seed)

        if self.ws_client is None:
            self._connect_ws()

        try:
            self.ws_client.send(json.dumps(payload))
            data = self._recv_reset_response()
        except Exception:
            self._connect_ws()
            self.ws_client.send(json.dumps(payload))
            data = self._recv_reset_response()

        info_data = data.get("info", {})
        controllable_ids = info_data.get("controllableAgentIds", [])
        if not controllable_ids:
            # Fallback if single agent
            controlled_id = info_data.get("controlledPlayerId", "left_1")
            controllable_ids = [controlled_id]

        self.possible_agents = list(controllable_ids)
        self.agents = list(self.possible_agents)

        # Observations list from reset response
        raw_obs_list = data.get("observations", [])
        if not raw_obs_list and "observation" in data:
            raw_obs_list = [data["observation"]]

        observations: Dict[str, np.ndarray] = {}
        for idx, agent in enumerate(self.agents):
            if idx < len(raw_obs_list):
                obs = np.array(raw_obs_list[idx], dtype=np.float32)
            else:
                obs = np.zeros(OBSERVATION_DIM, dtype=np.float32)
            observations[agent] = obs

        infos: Dict[str, Any] = {agent: dict(info_data) for agent in self.agents}
        return observations, infos

    def step(
        self,
        actions: Dict[str, int],
    ) -> Tuple[
        Dict[str, np.ndarray],
        Dict[str, float],
        Dict[str, bool],
        Dict[str, bool],
        Dict[str, Any],
    ]:
        """
        Executes a multi-agent joint action step.
        actions: mapping from agent ID to discrete action (0..18).
        """
        if not self.agents:
            return {}, {}, {}, {}, {}

        self._step_count += 1
        num_agents = len(self.agents)

        # Pack actions strictly in self.agents (controllableAgentIds) order
        action_bytes = bytearray(num_agents)
        for i, agent in enumerate(self.agents):
            act = int(actions.get(agent, 0))
            if not (0 <= act < ACTION_SPACE_SIZE):
                raise ValueError(
                    f"[GMN-PettingZoo] Invalid action {act} for agent {agent}. Must be in [0, {ACTION_SPACE_SIZE - 1}]."
                )
            action_bytes[i] = act

        if self.ws_client is None:
            self._connect_ws()

        try:
            self.ws_client.send(bytes(action_bytes))
            data, episode_stats = self._recv_step_response(num_agents)
        except Exception:
            self._connect_ws()
            self.ws_client.send(bytes(action_bytes))
            data, episode_stats = self._recv_step_response(num_agents)

        if isinstance(data, str):
            raise RuntimeError(f"[GMN-PettingZoo] Bridge sent text error: {data}")
        if not isinstance(data, (bytes, bytearray)):
            raise RuntimeError(f"[GMN-PettingZoo] Expected binary WebSocket frame, got {type(data)}")

        obs_bytes = OBSERVATION_DIM * 4
        expected_len = 17 + obs_bytes * num_agents
        if len(data) != expected_len:
            raise RuntimeError(
                f"[GMN-PettingZoo Frame Length Error] Expected {expected_len} bytes "
                f"(17B header + {obs_bytes}B * {num_agents} agents), but received {len(data)} bytes."
            )

        # Unpack 17-byte header
        reward, term, trunc, score_l, score_r, cp_reward, dist_goal, event_code = struct.unpack_from(
            "<f??BBffB", data, 0
        )

        shared_reward = float(reward)
        shared_term = bool(term)
        shared_trunc = bool(trunc)
        shared_info: Dict[str, Any] = {
            "score": {"left": int(score_l), "right": int(score_r)},
            "checkpointReward": float(cp_reward),
            "ballDistanceToGoal": float(dist_goal),
            "eventCode": int(event_code),
            "step": self._step_count,
        }
        if 0 < event_code < len(EVENT_CODE_MAP):
            ev_type = EVENT_CODE_MAP[event_code]
            if ev_type:
                shared_info["event"] = {"type": ev_type}

        # Attach ground-truth engine stats if the bridge sent them on episode end
        if episode_stats and shared_term:
            shared_info["ground_truth"] = {
                "possession_left_pct": episode_stats.get("possession_left_pct"),
                "completed_passes_left": episode_stats.get("completed_passes_left"),
                "attempted_passes_left": episode_stats.get("attempted_passes_left"),
                "shots_on_target_left": episode_stats.get("shots_on_target_left"),
                "total_shots_left": episode_stats.get("total_shots_left"),
                "pass_accuracy": (
                    episode_stats.get("completed_passes_left", 0) / episode_stats.get("attempted_passes_left", 1)
                    if episode_stats.get("attempted_passes_left", 0) > 0
                    else 0.0
                ),
                "shot_accuracy": (
                    episode_stats.get("shots_on_target_left", 0) / episode_stats.get("total_shots_left", 1)
                    if episode_stats.get("total_shots_left", 0) > 0
                    else 0.0
                ),
                "current_ball_owner": episode_stats.get("current_ball_owner"),
            }

        # Build per-step step_events for reward shaping from the single event_code
        step_events: List[Dict[str, Any]] = []
        if 0 < event_code < len(EVENT_CODE_MAP):
            ev_type = EVENT_CODE_MAP[event_code]
            if ev_type:
                # Infer team from score delta for goal events; otherwise assume left-team
                # action for offensive events and right-team for defensive/negative events.
                team = "left"
                if ev_type == "goal":
                    team = "left" if score_l > 0 else "right"
                elif ev_type in ("interception", "tackle", "foul"):
                    team = "right"

                step_events.append({"type": ev_type, "team": team})

        observations: Dict[str, np.ndarray] = {}
        rewards: Dict[str, float] = {}
        terminations: Dict[str, bool] = {}
        truncations: Dict[str, bool] = {}
        infos: Dict[str, Any] = {}

        for i, agent in enumerate(self.agents):
            offset = 17 + i * obs_bytes
            obs = np.frombuffer(data, dtype="<f4", count=OBSERVATION_DIM, offset=offset).copy()
            observations[agent] = obs
            rewards[agent] = shared_reward
            terminations[agent] = shared_term
            truncations[agent] = shared_trunc
            infos[agent] = dict(shared_info)
            if step_events:
                infos[agent]["step_events"] = step_events

        # Apply cooperative reward shaping if enabled
        if self.enable_reward_shaping and self.reward_shaper is not None and not shared_term and not shared_trunc:
            try:
                # Derive current ball owner from the first agent's observation
                current_ball_owner = None
                if self.agents:
                    first_obs = observations[self.agents[0]]
                    if len(first_obs) > 96:
                        no_one = float(first_obs[94])
                        left = float(first_obs[95])
                        right = float(first_obs[96])
                        if left > 0.5:
                            current_ball_owner = {"team": "left"}
                        elif right > 0.5:
                            current_ball_owner = {"team": "right"}

                shaped_rewards = self.reward_shaper.compute_shaped_rewards(
                    base_rewards=rewards,
                    step_events=step_events,
                    info_ground_truth={"current_ball_owner": current_ball_owner},
                    active_agents=list(self.agents),
                )
                for agent in self.agents:
                    if agent in shaped_rewards:
                        rewards[agent] = shaped_rewards[agent]
            except Exception as e:
                logger.debug(f"Reward shaping skipped due to error: {e}")

        if shared_term or shared_trunc:
            self.agents = []

        return observations, rewards, terminations, truncations, infos

    def render(self):
        """Render mode placeholder."""
        if self.render_mode == "human":
            print(f"[GMNMultiAgentEnv] Step: {self._step_count} | Agents: {self.possible_agents}")

    def close(self):
        """Cleans up WebSocket connection and bridge subprocess."""
        if self.ws_client is not None:
            try:
                self.ws_client.send(json.dumps({"type": "close"}))
                self.ws_client.close()
            except Exception:
                pass
            self.ws_client = None

        if self.bridge_process is not None:
            try:
                self.bridge_process.terminate()
                self.bridge_process.wait(timeout=2.0)
            except Exception:
                pass
            self.bridge_process = None

    def __getstate__(self):
        """Allows pickling by excluding unpicklable socket/process references."""
        state = self.__dict__.copy()
        state["ws_client"] = None
        state["bridge_process"] = None
        return state

    def __setstate__(self, state):
        """Restores state from pickle and marks client/process for lazy re-initialization."""
        self.__dict__.update(state)
        self.bridge_process = None
        self.ws_client = None
        self._needs_bridge = True
