import os
import time
import struct
import json
import subprocess
import requests
import numpy as np
import websockets.sync.client
import gymnasium as gym
from gymnasium import spaces
from typing import Optional, Tuple, Dict, Any, Union
import sys


def _npx_cmd():
    return ["npx.cmd"] if sys.platform == "win32" else ["npx"]


# --- P0.5d bridge startup budget ---------------------------------------------
# Unchanged from the pre-P0.5d loop: one spawn attempt followed by
# 24 re-checks. Sleeps total 1.0 + 24 * 0.4 = 10.6 s. The budget is NOT
# changed by P0.5d; only the failure behaviour when it is exhausted.
BRIDGE_STARTUP_ATTEMPTS = 25
BRIDGE_STARTUP_SLEEP_AFTER_SPAWN = 1.0
BRIDGE_STARTUP_SLEEP_BETWEEN = 0.4

# Marker that identifies a process as one of our bridge processes. Used to
# scope port reaping so an unrelated listener is never killed.
BRIDGE_PROCESS_MARKER = "bridge_server.ts"


def _parse_netstat_listening_pids(lines, port: int) -> set:
    """Extract Windows TCP-LISTENING pids for one local port.

    Deliberately strict: requires the row to be TCP (so UDP bind rows for the
    same port number are ignored) and to be in the LISTENING state.
    """
    port_text = str(port)
    pids = set()
    for line in lines:
        parts = line.split()
        if (
            len(parts) >= 5
            and parts[0].strip().upper() == "TCP"
            and parts[-2].strip().upper() == "LISTENING"
            and parts[1].rsplit(":", 1)[-1] == port_text
        ):
            pids.add(parts[-1])
    return pids


def _process_command_line(pid) -> str:
    """Best-effort command line lookup for a pid (empty string if unknown)."""
    if sys.platform != "win32":
        return ""
    try:
        out = subprocess.check_output(
            [
                "powershell",
                "-NoProfile",
                "-NonInteractive",
                "-Command",
                f"(Get-CimInstance Win32_Process -Filter \"ProcessId={pid}\").CommandLine",
            ],
            text=True,
            stderr=subprocess.DEVNULL,
            timeout=8.0,
        )
        return (out or "").strip()
    except Exception:
        return ""


# --- AUTOGENERATED CONTRACT CONSTANTS (DO NOT EDIT DIRECTLY) ---
# Generated from src/engine/Contract.ts by scripts/sync_contracts.ts
GMN_ENV_VERSION = "3.1.0"
OBSERVATION_SCHEMA_VERSION = "simple115_v3_role"
ACTION_SCHEMA_VERSION = "discrete19_v1"

ROLE_VOCABULARY = ["GK", "CB", "LB", "RB", "CDM", "CM", "LM", "RM", "LW", "RW", "CAM", "ST"]
ROLE_DIM = 12
BASE_OBSERVATION_DIM = 115
OBSERVATION_DIM = 127
ACTION_SPACE_SIZE = 19

EVENT_CODE_MAP = [
    None,
    "goal",
    "shot",
    "shot_saved",
    "shot_missed",
    "pass",
    "interception",
    "tackle",
    "foul",
    "kickoff",
    "out_of_bounds",
    "scenario_complete",
    "scenario_failed",
    "offside",
    "pass_completed",
    "pass_intercepted",
    "shot_blocked",
]
# --- END AUTOGENERATED CONTRACT CONSTANTS ---

# Hand-maintained transport constant (kept outside the autogenerated block).
# Every single-agent binary step frame ends with one 19-byte action mask after
# the observations (bridge_server.ts MASK_BYTES / encodeStepBinary). The mask
# was added in commit 2e130c8 ("Phase 11"); bridges before that sent
# header + observations only. GMNFootballEnv accepts both lengths explicitly so
# a real step reply is never silently discarded as an unsolicited broadcast -
# doing that turned every WebSocket step into a recv timeout.
MASK_BYTES = 19


def accepted_step_frame_lengths(scenario: str) -> set:
    """Return the binary step-frame lengths gmn_gym accepts for ``scenario``.

    Current bridge contract: ``header + OBSERVATION_DIM * 4 + MASK_BYTES``
    (545 bytes non-rondo, 549 bytes rondo). Legacy bridges: header +
    observations only (526 / 530 bytes).
    """
    header_size = 22 if scenario == "academy_rondo_4v1" else 18
    base_len = header_size + OBSERVATION_DIM * 4
    return {base_len, base_len + MASK_BYTES}


class GMNFootballEnv(gym.Env):
    """
    Gymnasium Environment wrapper for GMN-Football-3 Simulation.
    Communicates with the headless TypeScript GameEngine via binary WebSocket or HTTP Bridge.

    Authoritative Contract:
    - Observation Space: Box(-100.0, 100.0, shape=(127,), dtype=np.float32)
    - Action Space: Discrete(19)
    """

    metadata = {"render_modes": ["human", "rgb_array"], "render_fps": 60}

    def __init__(
        self,
        scenario: str = "academy_empty_goal",
        host: str = "127.0.0.1",
        port: Optional[int] = None,
        auto_start_bridge: bool = True,
        render_mode: Optional[str] = None,
        use_ws: bool = True,
        opponent_difficulty: str = "medium",
    ):
        super().__init__()

        self.scenario = scenario
        self.host = host
        self.port = port if port is not None else int(os.environ.get("GMN_BRIDGE_PORT", 5050))
        self.base_url = f"http://{self.host}:{self.port}"
        self.ws_url = f"ws://{self.host}:{self.port}"
        self.auto_start_bridge = auto_start_bridge
        self.render_mode = render_mode
        self.use_ws = use_ws
        self.bridge_process: Optional[subprocess.Popen] = None
        self.session = requests.Session()
        adapter = requests.adapters.HTTPAdapter(pool_connections=10, pool_maxsize=20, max_retries=3)
        self.session.mount("http://", adapter)
        self.ws_client = None
        # P0 #6: WebSocket receive timeout — the Python side must never hang
        # forever waiting for a bridge frame. Configurable via env.
        self.ws_recv_timeout = float(os.environ.get("GMN_WS_RECV_TIMEOUT", "10.0"))
        # 1. Observation Space: Exactly 127-float SMM Vector
        self.observation_space = spaces.Box(
            low=-100.0,
            high=100.0,
            shape=(OBSERVATION_DIM,),
            dtype=np.float32,
        )

        # 2. Action Space: Discrete(19) matching GMN-Football-3 canonical action space
        self.action_space = spaces.Discrete(ACTION_SPACE_SIZE)

        self._step_count = 0

        # Ensure Bridge Server is running
        self._ensure_bridge_running()
        if opponent_difficulty != "medium":
            self.set_opponent_difficulty(opponent_difficulty)
        if self.use_ws:
            self._connect_ws()

    def set_opponent_difficulty(self, difficulty: str) -> None:
        """Set the right-team (bot) difficulty via the bridge /opponent endpoint.

        Used by the self-play opponent pool (training/opponent_pool.py) to vary
        the opponent between episodes / vectorized workers.
        """
        if difficulty not in ("easy", "medium", "hard", "master"):
            raise ValueError(f"Invalid opponent difficulty: {difficulty}")
        try:
            res = self.session.post(
                f"{self.base_url}/opponent",
                json={"difficulty": difficulty},
                timeout=5.0,
            )
            if res.status_code != 200:
                raise RuntimeError(f"/opponent failed with code {res.status_code}: {res.text}")
        except requests.exceptions.ConnectionError:
            # Bridge without the /opponent endpoint (older bridge) — ignore.
            pass

    def _ensure_bridge_running(self):
        """Verifies connection to bridge server or starts it via npx tsx.

        P0.5d: the retry loop must never exit without a verified-healthy bridge.
        Before this change the ``for`` loop could fall through and return ``None``
        silently once the retry budget was exhausted, so the real failure
        surfaced much later as an unrelated WebSocket connect error inside
        ``_connect_ws``. It now raises immediately, with enough context to tell
        "bridge never became healthy" apart from a later frame/recv failure.

        The retry/sleep budget itself is unchanged (see
        ``BRIDGE_STARTUP_ATTEMPTS``).
        """
        attempts = 0
        last_health_error = "no health response received"
        for attempt in range(BRIDGE_STARTUP_ATTEMPTS):
            attempts = attempt + 1
            try:
                res = requests.get(f"{self.base_url}/health", timeout=1.0)
                if res.status_code == 200:
                    info = res.json()
                    bridge_obs_dim = info.get("observation_dim", 115)
                    bridge_act_dim = info.get("action_space_size", info.get("action_dim", 19))
                    if bridge_obs_dim != OBSERVATION_DIM or bridge_act_dim != ACTION_SPACE_SIZE:
                        raise RuntimeError(
                            f"[GMN-Gym Contract Mismatch] Bridge reports obs_dim={bridge_obs_dim}, "
                            f"act_dim={bridge_act_dim}; Expected obs_dim={OBSERVATION_DIM}, act_dim={ACTION_SPACE_SIZE}."
                        )
                    return
                last_health_error = f"HTTP {res.status_code}"
            except requests.RequestException as exc:
                last_health_error = f"{type(exc).__name__}: {exc}"

            if self.auto_start_bridge and self.bridge_process is None:
                print(f"[GMN-Gym] Launching Headless Bridge Server on {self.base_url}...")
                bridge_script = os.path.join(os.path.dirname(__file__), "bridge_server.ts")
                self.bridge_process = subprocess.Popen(
                    _npx_cmd() + ["tsx", bridge_script],
                    env=dict(os.environ, GMN_BRIDGE_PORT=str(self.port)),
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                time.sleep(BRIDGE_STARTUP_SLEEP_AFTER_SPAWN)
            else:
                time.sleep(BRIDGE_STARTUP_SLEEP_BETWEEN)

        # Reported budget depends on whether a bridge was actually spawned:
        #   spawned  -> 1.0 s after spawn + (N-1) x 0.4 s re-checks = 10.6 s
        #   no spawn -> N x 0.4 s re-checks                     = 10.0 s
        if self.bridge_process is not None:
            budget = (BRIDGE_STARTUP_SLEEP_AFTER_SPAWN
                      + (BRIDGE_STARTUP_ATTEMPTS - 1) * BRIDGE_STARTUP_SLEEP_BETWEEN)
        else:
            budget = BRIDGE_STARTUP_ATTEMPTS * BRIDGE_STARTUP_SLEEP_BETWEEN

        raise RuntimeError(
            f"[GMN-Gym Bridge Startup Failed] No healthy bridge on {self.base_url} "
            f"after {attempts} health checks (retry budget ~{budget:.1f}s). "
            f"Last health check result: {last_health_error}. "
            f"Bridge process was {'spawned by this env' if self.bridge_process is not None else 'NOT spawned (adopted existing listener or auto_start_bridge disabled)'}. "
            f"This is a bridge-startup/health failure and is distinct from a later "
            f"WebSocket connect or step-frame recv failure."
        )

    def _connect_ws(self):
        if self.ws_client is not None:
            try:
                self.ws_client.close()
            except Exception:
                pass
        for attempt in range(15):
            try:
                self.ws_client = websockets.sync.client.connect(
                    self.ws_url, max_size=None, ping_interval=None, open_timeout=5.0
                )
                return
            except Exception:
                time.sleep(0.2)
        self.ws_client = websockets.sync.client.connect(
            self.ws_url, max_size=None, ping_interval=None, open_timeout=5.0
        )

    def _recv_frame(self, operation: str):
        """
        P0 #6: Receive one WebSocket frame with a bounded timeout.

        Raises a clear RuntimeError (including the operation context) on
        timeout or connection failure instead of blocking forever. No
        automatic retries are performed — a retried `step` could duplicate an
        environment transition.
        """
        if self.ws_client is None:
            raise RuntimeError(f"[GMN-Gym WS Error] No WebSocket connection during '{operation}'.")
        try:
            return self.ws_client.recv(timeout=self.ws_recv_timeout)
        except TimeoutError:
            raise RuntimeError(
                f"[GMN-Gym WS Timeout] No frame received within {self.ws_recv_timeout}s "
                f"during '{operation}'. The bridge server is unresponsive."
            ) from None
        except RuntimeError as e:
            # websockets sync client raises RuntimeError("recv() with a timeout...")
            # on timeout in some versions; detect by message.
            if "timed out" in str(e).lower():
                raise RuntimeError(
                    f"[GMN-Gym WS Timeout] No frame received within {self.ws_recv_timeout}s "
                    f"during '{operation}'. The bridge server is unresponsive."
                ) from None
            raise RuntimeError(f"[GMN-Gym WS Error] during '{operation}': {e}") from e
        except Exception as e:
            raise RuntimeError(f"[GMN-Gym WS Error] during '{operation}': {e}") from e

    @staticmethod
    def _is_valid_reset_response(candidate: Any) -> bool:
        """
        P1 #13: Structural validation of a reset response.

        A valid reset response is a dict containing either:
          - 'observation': a list of exactly OBSERVATION_DIM floats, OR
          - 'observations': a non-empty list of per-agent observations, each
            exactly OBSERVATION_DIM floats.
        Unrelated parseable JSON (broadcasts, acks, errors) is rejected.
        """
        if not isinstance(candidate, dict):
            return False
        obs = candidate.get("observation")
        if isinstance(obs, (list, tuple)) and len(obs) == OBSERVATION_DIM:
            return True
        observations = candidate.get("observations")
        if (
            isinstance(observations, (list, tuple))
            and len(observations) > 0
            and all(isinstance(o, (list, tuple)) and len(o) == OBSERVATION_DIM for o in observations)
        ):
            return True
        return False

    def reset(
        self,
        *,
        seed: Optional[int] = None,
        options: Optional[Dict[str, Any]] = None,
    ) -> Tuple[np.ndarray, Dict[str, Any]]:
        super().reset(seed=seed)
        self._step_count = 0

        target_scenario = self.scenario
        if options and "scenario" in options:
            target_scenario = options["scenario"]

        payload: Dict[str, Any] = {
            "type": "reset",
            "scenario": target_scenario,
        }
        if seed is not None:
            payload["seed"] = int(seed)

        if self.use_ws:
            if self.ws_client is None:
                self._connect_ws()
            self.ws_client.send(json.dumps(payload))
            data = None
            for _ in range(60):
                frame = self._recv_frame("reset")
                if isinstance(frame, str):
                    try:
                        candidate = json.loads(frame)
                    except json.JSONDecodeError:
                        continue
                    # P1 #13: structural validation — unrelated parseable JSON
                    # (broadcasts, acks, errors) is NOT accepted as a reset.
                    if self._is_valid_reset_response(candidate):
                        data = candidate
                        break
                # else: unsolicited binary broadcast frame — skip
            if data is None:
                raise RuntimeError("[GMN-Gym WS Error] No structurally valid reset response received (only broadcast frames)")
            # BUG-4 follow-up: keep WS single-agent contract in sync — the
            # binary step path is header-size aware, so a scenario change via
            # reset() must update self.scenario for subsequent step() calls.
            self.scenario = target_scenario
        else:
            http_payload = {"scenario": target_scenario}
            if seed is not None:
                http_payload["seed"] = int(seed)
            res = self.session.post(f"{self.base_url}/reset", json=http_payload, timeout=5.0)
            if res.status_code != 200:
                raise RuntimeError(f"[GMN-Gym Bridge Error] /reset failed with code {res.status_code}: {res.text}")
            data = res.json()

        raw_obs = np.array(data["observation"], dtype=np.float32)
        if raw_obs.shape != (OBSERVATION_DIM,):
            raise ValueError(
                f"[GMN-Gym Contract Violation] Invalid observation shape {raw_obs.shape}. "
                f"Expected ({OBSERVATION_DIM},) floats without silent padding."
            )

        info = data.get("info", {})
        return raw_obs, info

    def step(
        self, action: int
    ) -> Tuple[np.ndarray, float, bool, bool, Dict[str, Any]]:
        if not self.action_space.contains(action):
            raise ValueError(f"Invalid action {action} for Discrete({ACTION_SPACE_SIZE}) space.")

        self._step_count += 1

        if self.use_ws:
            if self.ws_client is None:
                self._connect_ws()

            self.ws_client.send(int(action).to_bytes(1, "little"))
            # BUG-4 fix: rondo frames carry a 22B header (extra defenderReward
            # float32 at offset 20); non-rondo frames are 18B. Both the frame
            # length check and the observation slice must use the
            # scenario-specific header size, not hardcoded 18.
            header_size = 22 if self.scenario == "academy_rondo_4v1" else 18
            accepted_frame_lens = accepted_step_frame_lengths(self.scenario)
            data = None
            for _ in range(60):
                frame = self._recv_frame("step")
                if isinstance(frame, (bytes, bytearray)) and len(frame) in accepted_frame_lens:
                    data = frame
                    break
                # else: unsolicited broadcast (e.g. training_status / telemetry) — skip
            if data is None:
                raise RuntimeError(
                    f"[GMN-Gym WS Error] Expected a step frame of "
                    f"{sorted(accepted_frame_lens)} bytes, got only broadcast frames"
                )
            reward, term, trunc, score_l, score_r, cp_reward, dist_goal, event_code, _ball_owner_agent_idx = struct.unpack_from("<f??BBffBB", data, 0)
            raw_obs = np.frombuffer(data, dtype="<f4", count=OBSERVATION_DIM, offset=header_size).copy()

            # Bridge error-frame sentinel (P0 #5): an invalid action receives a
            # deterministic error frame instead of silence — surface it loudly.
            if reward <= -998.0 and bool(term):
                raise RuntimeError(
                    "[GMN-Gym Bridge Error] Bridge returned an error frame for the last action "
                    "(e.g. invalid action index). Check the action against Discrete(19)."
                )

            info: Dict[str, Any] = {
                "score": {"left": int(score_l), "right": int(score_r)},
                "checkpointReward": float(cp_reward),
                "ballDistanceToGoal": float(dist_goal),
            }
            if event_code > 0 and event_code < len(EVENT_CODE_MAP):
                ev_type = EVENT_CODE_MAP[event_code]
                if ev_type:
                    info["event"] = {"type": ev_type}

            return raw_obs, float(reward), bool(term), bool(trunc), info
        else:
            payload = {"action": int(action)}
            res = self.session.post(f"{self.base_url}/step", json=payload, timeout=5.0)
            if res.status_code != 200:
                raise RuntimeError(f"[GMN-Gym Bridge Error] /step failed with code {res.status_code}: {res.text}")
            data = res.json()

            raw_obs = np.array(data["observation"], dtype=np.float32)
            if raw_obs.shape != (OBSERVATION_DIM,):
                raise ValueError(
                    f"[GMN-Gym Contract Violation] Invalid observation shape {raw_obs.shape}. "
                    f"Expected ({OBSERVATION_DIM},) floats."
                )

            reward = float(data.get("reward", 0.0))
            terminated = bool(data.get("terminated", False))
            truncated = bool(data.get("truncated", False))
            info = data.get("info", {})

            return raw_obs, reward, terminated, truncated, info

    def render(self):
        if self.render_mode == "rgb_array":
            # TODO: Bridge /render endpoint not yet implemented. Returning placeholder.
            return np.zeros((360, 640, 3), dtype=np.uint8)
        elif self.render_mode == "human":
            print(f"[GMNFootballEnv Step {self._step_count}] Scenario: {self.scenario}")

    def _reap_bridge_on_port(self):
        """Free this env's bridge port by killing whatever is listening on it.

        P0.5d (defect 3): ``close()`` terminated only ``self.bridge_process``
        (the ``npx``/``tsx`` wrapper). ``npx.cmd`` can spawn a ``node.exe``
        grandchild that outlives the wrapper and keeps the port LISTENing, so
        on the SPAWNED path we additionally tree-kill the port listener.

        Scoping (important):
          * Only ever called when this env SPAWNED the bridge, i.e. it owns it.
          * An ADOPTED bridge is never killed. Ownership is absent and another
            env in the same process can legitimately share the same port --
            e.g. train_ppo reuses ``raw_env`` while eval_progress builds a
            second GMNFootballEnv on the same port. Killing an adopted bridge
            broke that sharing (ConnectionClosedError during final eval).
          * A listener whose command line is not a bridge is left running and
            reported, so unrelated system processes are never killed.
        """
        if sys.platform != "win32":
            return
        try:
            netstat = subprocess.check_output(
                ["netstat", "-ano"], text=True, stderr=subprocess.DEVNULL, timeout=5.0
            ).splitlines()
        except Exception:
            return

        for pid in sorted(_parse_netstat_listening_pids(netstat, self.port)):
            cmd = _process_command_line(pid)
            if cmd and BRIDGE_PROCESS_MARKER not in cmd:
                # Not one of ours - never kill an unrelated process.
                print(
                    f"[GMN-Gym] Port {self.port} listener pid={pid} is not a "
                    f"bridge process (cmd: {cmd[:120]!r}); leaving it running."
                )
                continue
            try:
                subprocess.check_call(
                    ["taskkill", "/F", "/T", "/PID", str(pid)],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    timeout=10.0,
                )
            except Exception:
                pass

    def close(self):
        if self.ws_client is not None:
            try:
                self.ws_client.send(json.dumps({"type": "close"}))
                self.ws_client.close()
            except Exception:
                pass
            self.ws_client = None
        try:
            self.session.close()
        except Exception:
            pass
        spawned_by_this_env = self.bridge_process is not None
        if spawned_by_this_env:
            try:
                requests.post(f"{self.base_url}/close", timeout=1.0)
            except Exception:
                pass
            self.bridge_process.terminate()
            self.bridge_process = None
            # P0.5d: we own this bridge, so tree-kill the port listener to catch
            # an npx/node grandchild that outlived the wrapper we just terminated.
            try:
                self._reap_bridge_on_port()
            except Exception:
                pass
