"""
GMN-Football-3 — PettingZoo Multi-Agent Parallel Environment Wrapper
Authoritative Environment Binding for Multi-Agent Football Simulation.

Wraps the GMN-Football-3 WebSocket bridge server as a PettingZoo ParallelEnv.
Supports simultaneous control of N left-team players with independent per-agent
observations (Box(115,)) and discrete action spaces (Discrete(19)).

NOTE: Connection/lifecycle helper methods are duplicated here from gmn_gym.py
as a deliberate isolation boundary to avoid touching verified single-agent code.
(Known follow-up cleanup opportunity: extract shared transport/lifecycle helpers).
"""

import os
import sys
import time
import json
import struct
import subprocess
import logging
from typing import Dict, List, Optional, Tuple, Any

import numpy as np
import requests
import websockets.sync.client
from gymnasium import spaces
from pettingzoo.utils.env import ParallelEnv

logger = logging.getLogger(__name__)

# Discrete action index for a shot attempt (ACTION_SPACE_SIZE == 19).
# Used by CooperativeRewardShaper to attribute the engine's SHOT_TAKEN event to
# the controlling agent(s) that actually commanded a shot when the binary frame
# reports the ball already in flight (no ball owner => event has no agent_id).
SHOT_ACTION_ID = 12


def _npx_cmd():
    return ["npx.cmd"] if sys.platform == "win32" else ["npx"]


# --- AUTOGENERATED CONTRACT CONSTANTS (DO NOT EDIT DIRECTLY) ---
# Generated from src/engine/Contract.ts by scripts/sync_contracts.ts
GMN_ENV_VERSION = "3.1.0"
OBSERVATION_SCHEMA_VERSION = "simple115_v3_role"
ACTION_SCHEMA_VERSION = "discrete19_v1"

ROLE_VOCABULARY = ["GK", "CB", "LB", "RB", "CDM", "CM", "LM", "RM", "LW", "RW", "CAM", "ST"]
ROLE_DIM = 12
BASE_OBSERVATION_DIM = 115
OBSERVATION_DIM = 127
ACTION_SPACE_SIZE = 19

EVENT_CODE_MAP = [
    None,
    "goal",
    "shot",
    "shot_saved",
    "shot_missed",
    "pass",
    "interception",
    "tackle",
    "foul",
    "kickoff",
    "out_of_bounds",
    "scenario_complete",
    "scenario_failed",
    "offside",
    "pass_completed",
    "pass_intercepted",
]
# --- END AUTOGENERATED CONTRACT CONSTANTS ---


class CooperativeRewardShaper:
    """
    Shapes agent rewards in GMN-Football-3 to encourage multi-agent passing
    and penalize unassisted direct shooting / excessive dribbling.
    """

    def __init__(
        self,
        reward_pass_completion: float = 0.30,
        reward_assisted_goal_bonus: float = 0.50,
        penalty_solitary_shot: float = -0.30,
        penalty_ball_hogging: float = -0.02,
        penalty_turnover: float = -0.10,
        max_unassisted_hold_ticks: int = 15,
    ):
        self.r_pass = reward_pass_completion
        self.r_assisted_goal = reward_assisted_goal_bonus
        self.p_solitary_shot = penalty_solitary_shot
        self.p_ball_hogging = penalty_ball_hogging
        self.p_turnover = penalty_turnover
        self.max_hold_ticks = max_unassisted_hold_ticks
        self.total_pass_completed_count: int = 0
        self.total_goal_scored_count: int = 0
        self.total_turnover_conceded_count: int = 0
        self.reset()

    def reset(self) -> None:
        """Reset sequence trackers at the start of an episode."""
        self.pass_chain_length: int = 0
        self.current_holder_id: Optional[str] = None
        self.holder_ticks: int = 0
        self.pass_completed_count: int = 0
        self.goal_scored_count: int = 0
        self.turnover_conceded_count: int = 0
        self.pass_intercepted_count: int = 0
        self.solitary_shot_count: int = 0
        self.assisted_goal_count: int = 0
        self.ball_hogging_count: int = 0

    def get_diagnostics(self) -> Dict[str, Any]:
        """Return episode-level cooperative shaping diagnostics."""
        return {
            "pass_chain_length": self.pass_chain_length,
            "holder_ticks": self.holder_ticks,
            "pass_completed_count": self.pass_completed_count,
            "goal_scored_count": self.goal_scored_count,
            "turnover_conceded_count": self.turnover_conceded_count,
            "pass_intercepted_count": self.pass_intercepted_count,
            "solitary_shot_count": self.solitary_shot_count,
            "assisted_goal_count": self.assisted_goal_count,
            "ball_hogging_count": self.ball_hogging_count,
        }

    def get_cumulative_diagnostics(self) -> Dict[str, Any]:
        """Return cumulative (cross-episode) event counters for live training logging."""
        return {
            "total_pass_completed_count": self.total_pass_completed_count,
            "total_goal_scored_count": self.total_goal_scored_count,
            "total_turnover_conceded_count": self.total_turnover_conceded_count,
        }

    def compute_shaped_rewards(
        self,
        base_rewards: Dict[str, float],
        step_events: List[Dict[str, Any]],
        info_ground_truth: Dict[str, Any],
        active_agents: List[str],
        actions: Optional[Dict[str, int]] = None,
    ) -> Dict[str, float]:
        """
        Calculates shaped rewards for all active left-team agents.
        Right-team agents (e.g. the defender in academy_rondo_4v1) are intentionally
        excluded because pass/assist/hogging terms are attacker-specific concepts.
        """
        shaped_rewards = {
            agent_id: base_rewards.get(agent_id, 0.0)
            for agent_id in active_agents
            if not agent_id.startswith("right_")
        }

        # Action cost: flat penalty for any ball-handling action to penalize spamming.
        BALL_ACTIONS = {9, 10, 11, 12, 17}
        if actions:
            for agent_id, action_idx in actions.items():
                if agent_id in shaped_rewards and action_idx in BALL_ACTIONS:
                    shaped_rewards[agent_id] -= 0.01

        # 1. Track Possession & Apply Ball-Hogging Penalties
        ball_owner = info_ground_truth.get("current_ball_owner") if info_ground_truth else None
        if isinstance(ball_owner, dict) and ball_owner.get("team") == "left":
            holder_id = ball_owner.get("agent_id")
            if holder_id and holder_id == self.current_holder_id:
                self.holder_ticks += 1
            else:
                self.current_holder_id = holder_id
                self.holder_ticks = 1

            if self.holder_ticks > self.max_hold_ticks and holder_id in shaped_rewards:
                shaped_rewards[holder_id] += self.p_ball_hogging
                self.ball_hogging_count += 1
        else:
            self.current_holder_id = None
            self.holder_ticks = 0

        # 2. Process Discrete Engine Events
        # M1: Some negative events are tagged team="right" by the engine because
        # the opposing team performed the interception/tackle/foul, but the
        # left-team agent identified in the event is the one who lost possession
        # and must receive the penalty. Process these regardless of event_team.
        _LEFT_TEAM_VICTIM_EVENT_TYPES = frozenset({
            "PASS_INTERCEPTED",
            "PASS_FAILED",
            "TURNOVER_CONCEDED",
        })
        for event in step_events:
            if not isinstance(event, dict):
                continue
            event_type = event.get("type")
            event_team = event.get("team")
            agent_id = event.get("agent_id")

            # M1: Negative events where left-team agent is the victim.
            if event_type in _LEFT_TEAM_VICTIM_EVENT_TYPES:
                if event_type == "PASS_INTERCEPTED":
                    self.pass_chain_length = 0
                    self.pass_intercepted_count += 1
                    self.total_turnover_conceded_count += 1
                    if agent_id in shaped_rewards:
                        shaped_rewards[agent_id] += self.p_turnover
                elif event_type in ("PASS_FAILED", "TURNOVER_CONCEDED"):
                    self.pass_chain_length = 0
                    self.turnover_conceded_count += 1
                    self.total_turnover_conceded_count += 1
                    if agent_id in shaped_rewards:
                        shaped_rewards[agent_id] += self.p_turnover
                continue

            # For all other events, only apply to left-team events.
            if event_team != "left":
                continue

            if event_type == "PASS_COMPLETED":
                self.pass_chain_length += 1
                self.pass_completed_count += 1
                self.total_pass_completed_count += 1
                if agent_id in shaped_rewards:
                    shaped_rewards[agent_id] += self.r_pass

            elif event_type == "SHOT_MISSED":
                if agent_id in shaped_rewards:
                    shaped_rewards[agent_id] -= 0.05

            elif event_type == "SHOT_TAKEN":
                # Penalize shots taken without a preceding completed pass in the
                # same possession chain (pass_chain_length == 0 => by definition
                # an unassisted shot; see test_solitary_shot_penalty_when_no_pass_chain).
                if self.pass_chain_length == 0:
                    # Attribution on the wire: the engine broadcasts the shot
                    # event on the frame the shot is released, when the ball is
                    # already in flight -- the bridge header then reports no ball
                    # owner (agent_id absent from the event). Fall back to charging
                    # every left-team agent that commanded a SHOT action this frame,
                    # so an unassisted-shot penalty cannot be dodged by spamming SHOT.
                    shot_agents: List[str] = []
                    if agent_id is not None and agent_id in shaped_rewards:
                        shot_agents = [agent_id]
                    elif actions:
                        shot_agents = [
                            act_agent
                            for act_agent, act_idx in actions.items()
                            if act_agent in shaped_rewards
                            and act_idx == SHOT_ACTION_ID
                        ]
                    for shot_agent in shot_agents:
                        shaped_rewards[shot_agent] += self.p_solitary_shot
                        self.solitary_shot_count += 1

            elif event_type == "GOAL_SCORED":
                # M2: The engine already provides the raw goal reward (e.g. +2.00)
                # in the step's base reward. Here we add the cooperative assisted-goal
                # bonus when the goal came from a pass chain.
                if self.pass_chain_length > 0:
                    for active_agent in active_agents:
                        if active_agent in shaped_rewards:
                            shaped_rewards[active_agent] += self.r_assisted_goal
                    self.assisted_goal_count += 1
                self.goal_scored_count += 1
                self.total_goal_scored_count += 1
                self.pass_chain_length = 0

        return shaped_rewards


# --- AUTOGENERATED CONTRACT CONSTANTS (DO NOT EDIT DIRECTLY) ---
# Generated from src/engine/Contract.ts by scripts/sync_contracts.ts
GMN_ENV_VERSION = "3.1.0"
OBSERVATION_SCHEMA_VERSION = "simple115_v3_role"
ACTION_SCHEMA_VERSION = "discrete19_v1"

ROLE_VOCABULARY = ["GK", "CB", "LB", "RB", "CDM", "CM", "LM", "RM", "LW", "RW", "CAM", "ST"]
ROLE_DIM = 12
BASE_OBSERVATION_DIM = 115
OBSERVATION_DIM = 127
ACTION_SPACE_SIZE = 19

EVENT_CODE_MAP = [
    None,
    "goal",
    "shot",
    "shot_saved",
    "shot_missed",
    "pass",
    "interception",
    "tackle",
    "foul",
    "kickoff",
    "out_of_bounds",
    "scenario_complete",
    "scenario_failed",
    "offside",
    "pass_completed",
    "pass_intercepted",
]
# --- END AUTOGENERATED CONTRACT CONSTANTS ---


class GMNMultiAgentEnv(ParallelEnv):
    """
    PettingZoo ParallelEnv wrapper for GMN-Football-3 multi-agent scenarios.
    Controls N players on the left team simultaneously.
    """

    metadata = {
        "render_modes": ["human", "rgb_array"],
        "name": "gmn_football_multiagent_v3",
    }

    def __init__(
        self,
        scenario: str = "academy_3_vs_1_with_keeper",
        host: str = "127.0.0.1",
        port: Optional[int] = None,
        auto_start_bridge: bool = True,
        render_mode: Optional[str] = None,
        enable_reward_shaping: bool = True,
        opponent_difficulty: str = "medium",
        opponent_pool: Optional[Any] = None,
        batch_size: int = 1,
        debug_rewards: bool = False,
    ):
        super().__init__()
        self.scenario = scenario
        self.host = host
        self.port = port or int(os.environ.get("GMN_BRIDGE_PORT", "5050"))
        self.base_url = f"http://{self.host}:{self.port}"
        self.ws_url = f"ws://{self.host}:{self.port}"
        if debug_rewards:
            self.ws_url += "?debug=rewards"
        self.auto_start_bridge = auto_start_bridge
        self.render_mode = render_mode
        self.enable_reward_shaping = enable_reward_shaping
        self.opponent_difficulty = opponent_difficulty
        self.opponent_pool = opponent_pool
        self.current_opponent: Optional[Dict[str, Any]] = None
        self.batch_size = max(1, int(batch_size))
        self.debug_rewards = debug_rewards
        self.reward_components: List[Dict[str, Any]] = []
        self.bridge_process: Optional[subprocess.Popen] = None
        self.ws_client = None
        self.reward_shaper = CooperativeRewardShaper() if enable_reward_shaping else None
        self._pending_pass: Optional[Dict[str, Any]] = None
        # Per-env rollout state for batched mode: list of dicts with keys
        # obs_dict, ep_rew, ep_len, agents, possible_agents, agent_order, obs_dim
        self._batch_envs: List[Dict[str, Any]] = []

        self._step_count = 0
        self.agents: List[str] = []
        self.possible_agents: List[str] = []

        # Phase 5: forensic debug flag and episode index
        self._forensic_debug: bool = os.environ.get("GMN_FORENSIC_DEBUG", "0") == "1"
        self._episode_index: int = 0
        self._bridge_error_count: int = 0

        # Terminal-frame provenance for forensic reward tracing (Step 2/3).
        # These are set on every step() call; on terminal ticks they capture
        # the exact values that flowed through the pipeline at episode end.
        self._last_frame_reward: float = 0.0
        self._last_frame_event_code: int = 0
        self._last_frame_score: Dict[str, int] = {"left": 0, "right": 0}
        self._last_shared_reward: float = 0.0

        # Observation and action spaces (identical across all agents)
        self._obs_space = spaces.Dict({
            "observation": spaces.Box(
                low=-100.0,
                high=100.0,
                shape=(OBSERVATION_DIM,),
                dtype=np.float32,
            ),
            "action_mask": spaces.Box(
                low=0,
                high=1,
                shape=(19,),
                dtype=np.int8,
            ),
        })
        self._act_space = spaces.Discrete(ACTION_SPACE_SIZE)

        # Ensure Bridge Server is running & connected
        self._ensure_bridge_running()
        # P0 #6: bounded WS receive timeout (never hang on a missing frame).
        self.ws_recv_timeout = float(os.environ.get("GMN_WS_RECV_TIMEOUT", "10.0"))
        if self.auto_start_bridge:
            self._connect_ws()

        # Perform initial reset to discover controllable agents.
        # When auto_start_bridge=False (e.g. unit tests injecting a mock WS),
        # skip reset so ws_client stays None until the caller sets it.
        if self.auto_start_bridge:
            self.reset()

        # Set opponent difficulty AFTER bridge is fully ready and connected.
        # Calling before _connect_ws() can fail silently if the bridge was just
        # started and its /opponent endpoint is not yet accepting requests.
        if opponent_difficulty != "medium":
            self.set_opponent_difficulty(opponent_difficulty)

    def set_opponent_difficulty(self, difficulty: str) -> None:
        """Set the right-team (bot) difficulty via the bridge /opponent endpoint."""
        if difficulty not in ("easy", "medium", "hard", "master"):
            raise ValueError(f"Invalid opponent difficulty: {difficulty}")
        self.opponent_difficulty = difficulty
        try:
            import requests  # already a module dependency of this wrapper

            requests.post(
                f"http://{self.host}:{self.port}/opponent",
                json={"difficulty": difficulty},
                timeout=5.0,
            )
        except Exception:
            pass  # older bridges without /opponent keep the default difficulty

    def set_scenario(self, scenario: str) -> None:
        """Switch the active scenario and clear rollout state so the next reset uses it."""
        self.scenario = scenario
        # Clear MAPPO rollout scratch state so collect_rollout() re-initializes
        # from the new scenario rather than replaying stale observations.
        self._mappo_obs = None
        self._mappo_ep_rew = 0.0
        self._mappo_ep_len = 0
        self._pending_pass = None
        if hasattr(self, "_batch_envs"):
            self._batch_envs = []

    def _decode_reset_result(self, result: Dict[str, Any]) -> Dict[str, Any]:
        """Decode one reset response payload into a per-env rollout state dict."""
        info_data = result.get("info", {})
        controllable_ids = info_data.get("controllableAgentIds", [])
        if not controllable_ids:
            controlled_id = info_data.get("controlledPlayerId", "left_1")
            controllable_ids = [controlled_id]
        raw_obs_list = result.get("observations", [])
        if not raw_obs_list and "observation" in result:
            raw_obs_list = [result["observation"]]
        observations: Dict[str, np.ndarray] = {}
        for idx, agent in enumerate(controllable_ids):
            if idx < len(raw_obs_list):
                obs = np.array(raw_obs_list[idx], dtype=np.float32)
            else:
                obs = np.zeros(OBSERVATION_DIM, dtype=np.float32)
            observations[agent] = obs
        action_masks = {agent: np.ones(19, dtype=np.int8) for agent in controllable_ids}
        batched_obs = {
            agent: {"observation": observations[agent], "action_mask": action_masks[agent]}
            for agent in controllable_ids
        }
        return {
            "obs_dict": batched_obs,
            "action_masks": action_masks,
            "possible_agents": list(controllable_ids),
            "agents": list(controllable_ids),
            "agent_order": list(controllable_ids),
            "obs_dim": OBSERVATION_DIM,
            "ep_rew": 0.0,
            "ep_len": 0,
            "info": dict(info_data),
        }

    def _init_batch_envs(self, batch_results: List[Dict[str, Any]]) -> None:
        """Initialize per-env rollout state from a batch reset response."""
        self._batch_envs = []
        for result in batch_results:
            env_state = self._decode_reset_result(result)
            # M5: Per-env reward-shaping state so the batched path applies the
            # same cooperative curriculum as the single-env path.
            env_state["pending_pass"] = None
            env_state["reward_shaper"] = CooperativeRewardShaper() if self.enable_reward_shaping else None
            env_state["last_actions"] = {}
            self._batch_envs.append(env_state)

    def reset_batch(self, seeds: Optional[List[int]] = None) -> List[Tuple[Dict[str, np.ndarray], Dict[str, Any]]]:
        """Reset all sub-environments in the batch and return per-env (obs, info) tuples."""
        seeds = seeds or [42] * self.batch_size
        requests = []
        for idx, s in enumerate(seeds[: self.batch_size]):
            req: Dict[str, Any] = {"scenario": self.scenario}
            if s is not None:
                req["seed"] = int(s)
            else:
                req["seed"] = 42 + idx
            requests.append(req)
        while len(requests) < self.batch_size:
            requests.append({"scenario": self.scenario, "seed": 42 + len(requests)})
        payload = json.dumps({"type": "reset_batch", "environments": requests})
        if self.ws_client is None:
            self._connect_ws()
        try:
            self.ws_client.send(payload)
            data = self._recv_reset_batch_response()
        except Exception:
            self._connect_ws()
            self.ws_client.send(payload)
            data = self._recv_reset_batch_response()
        parsed = json.loads(data) if isinstance(data, str) else {}
        if not isinstance(parsed, dict):
            raise RuntimeError(f"[GMN-Batch] Expected dict reset response, got {type(parsed)}")
        results = parsed.get("results", [])
        if len(results) != self.batch_size:
            raise RuntimeError(f"[GMN-Batch] Expected {self.batch_size} reset results, got {len(results)}: {list(parsed.keys())}")
        self._init_batch_envs(results)
        # Return per-env tuples for the caller (trainer can index by env_idx)
        return [
            (env_state["obs_dict"], {a: env_state["info"] for a in env_state["agents"]})
            for env_state in self._batch_envs
        ]

    def reset_one(
        self, env_idx: int, seed: Optional[int] = None
    ) -> Tuple[Dict[str, np.ndarray], Dict[str, Any]]:
        """Reset a single sub-environment in the batch (G6 fix).

        Mirrors collect_rollout_parallel's reset-on-terminal: a terminated
        sub-env is revived immediately instead of idling until the whole batch
        is dead. Returns (obs_dict, info) in the same envelope format as
        reset_batch; self._batch_envs[env_idx] is replaced with fresh state.
        """
        if not (0 <= env_idx < self.batch_size):
            raise IndexError(
                f"[GMN-Batch] reset_one index {env_idx} out of range (batch_size={self.batch_size})"
            )
        payload = json.dumps({
            "type": "reset_one",
            "index": int(env_idx),
            "scenario": self.scenario,
            "seed": int(seed) if seed is not None else 42 + env_idx,
        })
        if self.ws_client is None:
            self._connect_ws()
        try:
            self.ws_client.send(payload)
            data = self._recv_reset_one_response()
        except Exception:
            self._connect_ws()
            self.ws_client.send(payload)
            data = self._recv_reset_one_response()
        parsed = json.loads(data) if isinstance(data, str) else {}
        if not isinstance(parsed, dict) or parsed.get("type") != "reset_one_result":
            raise RuntimeError(f"[GMN-Batch] Expected reset_one_result, got: {list(parsed.keys()) if isinstance(parsed, dict) else type(parsed)}")
        result = parsed.get("result")
        if not isinstance(result, dict):
            raise RuntimeError(f"[GMN-Batch] reset_one({env_idx}) missing result payload")
        state = self._decode_reset_result(result)
        self._batch_envs[env_idx] = state
        return (state["obs_dict"], {a: state["info"] for a in state["agents"]})

    def _recv_reset_one_response(self) -> str:
        """Receive a reset_one JSON response, skipping unsolicited broadcast frames."""
        for _ in range(60):
            data = self._recv_frame("reset_one")
            if isinstance(data, str):
                try:
                    parsed = json.loads(data)
                    if isinstance(parsed, dict) and parsed.get("type") == "reset_one_result":
                        return data
                except (json.JSONDecodeError, AttributeError):
                    pass
        raise RuntimeError("[GMN-Batch] No reset_one_result received (only broadcast frames)")

    def step_batch(
        self, action_sets: List[Dict[str, int]]
    ) -> List[Tuple[Dict[str, np.ndarray], Dict[str, float], Dict[str, bool], Dict[str, bool], Dict[str, Any]]]:
        """Step all sub-environments with their respective action dicts."""
        if len(action_sets) != self.batch_size:
            raise RuntimeError(f"[GMN-Batch] step_batch expects {self.batch_size} action dicts, got {len(action_sets)}")
        action_bytes_per_env: List[bytes] = []
        controllable_ids_per_env: List[List[str]] = []
        for env_idx, actions in enumerate(action_sets):
            env_state = self._batch_envs[env_idx]
            current_agents = env_state["agents"]
            num_agents = len(current_agents)
            action_bytes = bytearray(num_agents)
            for i, agent in enumerate(current_agents):
                act = int(actions.get(agent, 0))
                if not (0 <= act < ACTION_SPACE_SIZE):
                    raise ValueError(f"[GMN-Batch] Invalid action {act} for agent {agent}")
                action_bytes[i] = act
            action_bytes_per_env.append(bytes(action_bytes))
            controllable_ids_per_env.append(current_agents)
            # M5: Store actions for reward-shaping attribution (solitary shot, etc.).
            env_state["last_actions"] = dict(actions)
        # Build batched binary frame: [0xFF (1B)] [B (1B)] [N (1B)] [B * N action bytes]
        N = len(controllable_ids_per_env[0]) if controllable_ids_per_env else 0
        frame = bytearray(3 + self.batch_size * N)
        frame[0] = 0xFF
        frame[1] = self.batch_size
        frame[2] = N
        for env_idx, action_bytes in enumerate(action_bytes_per_env):
            offset = 3 + env_idx * N
            frame[offset : offset + N] = action_bytes
        if self.ws_client is None:
            self._connect_ws()
        try:
            self.ws_client.send(bytes(frame))
            data = self._recv_batch_response()
        except Exception as e:
            # Log bridge errors for forensic debugging
            if getattr(self, "_forensic_debug", False):
                import sys as _sys
                print(
                    f"[FORENSIC_BRIDGE_ERROR]\n"
                    f"scenario={self.scenario}\n"
                    f"global_step={self._step_count}\n"
                    f"error_type={type(e).__name__}\n"
                    f"error_message={str(e)}\n"
                    f"bridge_error_count={getattr(self, '_bridge_error_count', 0)}\n"
                    f"batch_size={self.batch_size}\n"
                    f"[END_FORENSIC_BRIDGE_ERROR]",
                    flush=True,
                    file=_sys.stderr,
                )
            self._connect_ws()
            self.ws_client.send(bytes(frame))
            data = self._recv_batch_response()
        if isinstance(data, str):
            raise RuntimeError(f"[GMN-Batch] Bridge sent text error: {data}")
        obs_bytes = OBSERVATION_DIM * 4
        is_rondo = self.scenario == "academy_rondo_4v1"
        header_size = 22 if is_rondo else 18
        mask_bytes = 19
        frame_size = header_size + obs_bytes * N + mask_bytes * N
        expected_len = 2 + self.batch_size * frame_size
        if len(data) != expected_len:
            raise RuntimeError(
                f"[GMN-Batch Frame Length Error] Expected {expected_len} bytes, got {len(data)} bytes"
            )
        results: List[Tuple[Dict[str, np.ndarray], Dict[str, float], Dict[str, bool], Dict[str, bool], Dict[str, Any]]] = []
        for env_idx in range(self.batch_size):
            env_state = self._batch_envs[env_idx]
            base_offset = 2 + env_idx * frame_size
            reward, term, trunc, score_l, score_r, cp_reward, dist_goal, event_code, ball_owner_agent_idx = struct.unpack_from(
                "<f??BBffBB", data, base_offset
            )
            # Bridge error-frame sentinel (P0 #5): surface loudly instead of silently
            # accumulating a -999 penalty into episode reward.
            if float(reward) <= -998.0 and bool(term):
                self._bridge_error_count += 1
                raise RuntimeError(
                    f"[GMN-PettingZoo Bridge Error] Bridge returned an error frame for "
                    f"env_idx={env_idx} (reward <= -998.0, terminated=true). This "
                    f"indicates an internal bridge error. Check the bridge server logs."
                )
            defender_reward = 0.0
            if is_rondo:
                defender_reward = struct.unpack_from("<f", data, base_offset + 18)[0]
            shared_reward = float(reward)
            shared_term = bool(term)
            shared_trunc = bool(trunc)
            shared_info: Dict[str, Any] = {
                "score": {"left": int(score_l), "right": int(score_r)},
                "checkpointReward": float(cp_reward),
                "ballDistanceToGoal": float(dist_goal),
                "eventCode": int(event_code),
                "step": env_state.get("ep_len", 0),
            }
            if 0 < event_code < len(EVENT_CODE_MAP):
                ev_type = EVENT_CODE_MAP[event_code]
                if ev_type:
                    shared_info["event"] = {"type": ev_type}
            observations: Dict[str, Any] = {}
            action_masks: Dict[str, np.ndarray] = {}
            terminal_agents = list(env_state["agents"])
            for i, agent in enumerate(terminal_agents):
                offset = base_offset + header_size + i * obs_bytes
                obs = np.frombuffer(data, dtype="<f4", count=OBSERVATION_DIM, offset=offset).copy()
                mask_offset = base_offset + header_size + N * obs_bytes + i * 19
                mask = np.frombuffer(data, dtype="<u1", count=19, offset=mask_offset).copy().astype(np.int8)
                observations[agent] = {"observation": obs, "action_mask": mask}
                action_masks[agent] = mask
            batched_obs = {
                agent: {"observation": observations[agent]["observation"], "action_mask": action_masks[agent]}
                for agent in terminal_agents
            }
            env_state["obs_dict"] = batched_obs
            env_state["action_masks"] = action_masks
            env_state["ep_rew"] += shared_reward
            env_state["ep_len"] += 1
            if shared_term or shared_trunc:
                env_state["agents"] = []
                shared_info["episode_length_steps"] = env_state.get("ep_len", 0)
                shared_info["episode_physics_ticks"] = env_state.get("ep_len", 0)
            if is_rondo:
                env_rewards = {
                    agent: defender_reward if agent.startswith("right_") else shared_reward
                    for agent in terminal_agents
                }
            else:
                # M5: Normalize non-rondo rewards to a per-agent dict so shaping
                # can add cooperative bonuses on top.
                env_rewards = {agent: shared_reward for agent in terminal_agents}

            # M5: Apply cooperative reward shaping per sub-environment so the
            # batched path exercises the same curriculum as the single-env path.
            shaped_rewards = self._apply_shaping_for_env(
                env_state=env_state,
                shared_reward=shared_reward,
                shared_term=shared_term,
                shared_trunc=shared_trunc,
                event_code=event_code,
                ball_owner_agent_idx=ball_owner_agent_idx,
                score_l=score_l,
                score_r=score_r,
                actions=env_state.get("last_actions", {}),
            )
            if shaped_rewards:
                for agent in terminal_agents:
                    if agent in shaped_rewards:
                        env_rewards[agent] = shaped_rewards[agent]

            results.append((observations, env_rewards, shared_term, shared_trunc, shared_info))
        return results

    def _recv_batch_response(self) -> bytes:
        """Receive one batched binary step response, skipping unsolicited broadcast frames."""
        for _ in range(60):
            data = self._recv_frame("step_batch")
            if isinstance(data, (bytes, bytearray)):
                return bytes(data)
        raise RuntimeError("[GMN-Batch] No binary batch response received (only broadcast frames)")

    def _recv_reset_batch_response(self) -> str:
        """Receive a reset_batch JSON response, skipping unsolicited broadcast frames."""
        for _ in range(60):
            data = self._recv_frame("reset_batch")
            if isinstance(data, str):
                try:
                    parsed = json.loads(data)
                    if isinstance(parsed, dict) and parsed.get("type") == "reset_batch_result":
                        return data
                except (json.JSONDecodeError, AttributeError):
                    pass
        raise RuntimeError("[GMN-Batch] No reset_batch_result received (only broadcast frames)")

    def _ensure_bridge_running(self):
        """Verifies connection to bridge server or starts it via npx tsx."""
        for attempt in range(6):
            try:
                res = requests.get(f"{self.base_url}/health", timeout=1.0)
                if res.status_code == 200:
                    info = res.json()
                    bridge_obs_dim = info.get("observation_dim", 115)
                    bridge_act_dim = info.get("action_space_size", info.get("action_dim", 19))
                    if bridge_obs_dim != OBSERVATION_DIM or bridge_act_dim != ACTION_SPACE_SIZE:
                        raise RuntimeError(
                            f"[GMN-PettingZoo Contract Mismatch] Bridge reports obs_dim={bridge_obs_dim}, "
                            f"act_dim={bridge_act_dim}; Expected obs_dim={OBSERVATION_DIM}, act_dim={ACTION_SPACE_SIZE}."
                        )
                    return
            except requests.RequestException:
                pass

            if self.auto_start_bridge and self.bridge_process is None:
                print(f"[GMN-PettingZoo] Launching Headless Bridge Server on {self.base_url}...")
                bridge_script = os.path.join(os.path.dirname(__file__), "bridge_server.ts")
                self.bridge_process = subprocess.Popen(
                    _npx_cmd() + ["tsx", bridge_script],
                    env=dict(os.environ, GMN_BRIDGE_PORT=str(self.port)),
                )
                time.sleep(2.0)
            else:
                time.sleep(1.0)


    def _connect_ws(self):
        """Establishes or reconnects WebSocket client connection."""
        if self.ws_client is not None:
            try:
                self.ws_client.close()
            except Exception:
                pass
        self.ws_client = websockets.sync.client.connect(
            self.ws_url, max_size=None, ping_interval=None, open_timeout=5.0
        )

    def _recv_frame(self, operation: str):
        """
        P0 #6: Receive one WebSocket frame with a bounded timeout. Raises a
        clear RuntimeError (with operation context) on timeout instead of
        blocking forever. No automatic retries (a retried step could duplicate
        an environment transition).
        """
        if self.ws_client is None:
            raise RuntimeError(f"[GMN-PettingZoo WS Error] No WebSocket connection during '{operation}'.")
        try:
            return self.ws_client.recv(timeout=self.ws_recv_timeout)
        except TimeoutError:
            raise RuntimeError(
                f"[GMN-PettingZoo WS Timeout] No frame received within {self.ws_recv_timeout}s "
                f"during '{operation}'. The bridge server is unresponsive."
            ) from None
        except RuntimeError as e:
            if "timed out" in str(e).lower():
                raise RuntimeError(
                    f"[GMN-PettingZoo WS Timeout] No frame received within {self.ws_recv_timeout}s "
                    f"during '{operation}'. The bridge server is unresponsive."
                ) from None
            raise RuntimeError(f"[GMN-PettingZoo WS Error] during '{operation}': {e}") from e
        except Exception as e:
            raise RuntimeError(f"[GMN-PettingZoo WS Error] during '{operation}': {e}") from e

    def observation_space(self, agent: str) -> spaces.Space:
        """Returns the observation space for the given agent."""
        return self._obs_space

    def action_space(self, agent: str) -> spaces.Space:
        """Returns the action space for the given agent."""
        return self._act_space

    def _recv_reset_response(self) -> Dict[str, Any]:
        """Receive a reset response, skipping unsolicited broadcast frames ON the shared WS.

        P1 #13: structural validation — a valid reset response must contain
        'observation' or 'observations' with the correct OBSERVATION_DIM shape.
        """
        for _ in range(60):
            frame = self._recv_frame("reset")
            if isinstance(frame, str):
                try:
                    candidate = json.loads(frame)
                except json.JSONDecodeError:
                    continue
                if self._is_valid_reset_response(candidate):
                    return candidate
            # unsolicited broadcast / malformed frame — skip
        raise RuntimeError("[GMN-PettingZoo] No structurally valid reset response received (only broadcast frames)")

    @staticmethod
    def _is_valid_reset_response(candidate: Any) -> bool:
        """P1 #13: structural validation of a reset response payload."""
        if not isinstance(candidate, dict):
            return False
        obs = candidate.get("observation")
        if isinstance(obs, (list, tuple)) and len(obs) == OBSERVATION_DIM:
            return True
        observations = candidate.get("observations")
        if (
            isinstance(observations, (list, tuple))
            and len(observations) > 0
            and all(isinstance(o, (list, tuple)) and len(o) == OBSERVATION_DIM for o in observations)
        ):
            return True
        return False

    def _recv_step_response(self, num_agents: int) -> Tuple[bytes, Optional[Dict[str, Any]], float]:
        """Receive a binary step response, skipping unsolicited broadcast frames ON the shared WS.
        
        Also collects any EPISODE_STATS JSON frames that arrive alongside the binary response.
        Returns (binary_data, episode_stats, defender_reward).
        """
        obs_bytes = OBSERVATION_DIM * 4
        is_rondo = self.scenario == "academy_rondo_4v1"
        header_size = 22 if is_rondo else 18
        mask_bytes = 19
        expected_len = header_size + obs_bytes * num_agents + mask_bytes * num_agents
        episode_stats: Optional[Dict[str, Any]] = None
        defender_reward = 0.0
        reward_components: Optional[Dict[str, Any]] = None
        for _ in range(60):
            data = self._recv_frame("step")
            if isinstance(data, (bytes, bytearray)) and len(data) == expected_len:
                # Phase 1: forensic binary terminal-frame capture
                raw_reward, term, trunc, score_l, score_r, cp_reward, dist_goal, event_code, ball_owner_agent_idx = struct.unpack_from(
                    "<f??BBffBB", data, 0
                )
                if is_rondo:
                    defender_reward = struct.unpack_from("<f", data, 18)[0]
                if getattr(self, "_forensic_debug", False) and (term or trunc):
                    print(
                        f"[FORENSIC_BINARY_TERMINAL]\n"
                        f"scenario={self.scenario}\n"
                        f"episode={getattr(self, '_episode_index', -1)}\n"
                        f"global_step={self._step_count}\n"
                        f"frame_length={len(data)}\n"
                        f"expected_frame_length={expected_len}\n"
                        f"\n"
                        f"raw_reward={raw_reward}\n"
                        f"terminated={bool(term)}\n"
                        f"truncated={bool(trunc)}\n"
                        f"\n"
                        f"score_left={score_l}\n"
                        f"score_right={score_r}\n"
                        f"\n"
                        f"checkpoint_reward={cp_reward}\n"
                        f"distance_to_goal={dist_goal}\n"
                        f"event_code={event_code}\n"
                        f"ball_owner_agent_idx={ball_owner_agent_idx}\n"
                        f"\n"
                        f"defender_reward={defender_reward}\n"
                        f"parsed_observation_offset={header_size}\n"
                        f"reward_offset=0\n"
                        f"{'ATTACKER_REWARD_FROM_OFFSET_0' if is_rondo else 'STANDARD_REWARD_FROM_OFFSET_0'}\n"
                        f"{'DEFENDER_REWARD_FROM_OFFSET_18' if is_rondo else 'NON_RONDO_NO_DEFENDER_FIELD'}\n"
                        f"[END_FORENSIC_BINARY_TERMINAL]",
                        flush=True,
                    )
                if self.debug_rewards and reward_components is None:
                    reward_components = {}
                return bytes(data), episode_stats, defender_reward, reward_components
            # Collect EPISODE_STATS and REWARD_COMPONENTS JSON frames
            if isinstance(data, str):
                try:
                    parsed = json.loads(data)
                    if isinstance(parsed, dict):
                        if parsed.get("type") == "EPISODE_STATS":
                            episode_stats = parsed
                            continue
                        if parsed.get("type") == "REWARD_COMPONENTS":
                            reward_components = parsed.get("data")
                            continue
                except (json.JSONDecodeError, AttributeError):
                    pass
            # unsolicited broadcast (training_status/telemetry) — skip
        raise RuntimeError(
            f"[GMN-PettingZoo Frame Length Error] Expected {expected_len} bytes, got only broadcast frames"
        )

    def reset(
        self,
        seed: Optional[int] = None,
        options: Optional[Dict[str, Any]] = None,
    ) -> Tuple[Dict[str, np.ndarray], Dict[str, Any]]:
        """
        Resets the multi-agent environment and returns per-agent initial observations.
        """
        if getattr(self, "_needs_bridge", False):
            self._ensure_bridge_running()
            self._connect_ws()
            self._needs_bridge = False

        self._step_count = 0
        self._episode_index += 1
        self.reward_components = []
        if self.reward_shaper is not None:
            self.reward_shaper.reset()
        self._pending_pass = None

        # Self-play / opponent-pool selection: pick an opponent for this episode.
        if self.opponent_pool is not None:
            self.current_opponent = self.opponent_pool.sample()
            self.opponent_pool.apply(self.current_opponent, self)

        target_scenario = self.scenario
        if options and "scenario" in options:
            target_scenario = options["scenario"]

        # Batched mode: reset all sub-envs via the bridge pool and expose the
        # first sub-env through the standard PettingZoo reset() contract.
        if self.batch_size > 1:
            seeds = [int(seed) + i if seed is not None else None for i in range(self.batch_size)]
            batch_results = self.reset_batch(seeds)
            first_obs, first_info = batch_results[0]
            self.possible_agents = list(first_obs.keys())
            self.agents = list(self.possible_agents)
            return first_obs, first_info

        payload: Dict[str, Any] = {
            "type": "reset",
            "scenario": target_scenario,
        }
        if seed is not None:
            payload["seed"] = int(seed)

        if self.ws_client is None:
            self._connect_ws()

        try:
            self.ws_client.send(json.dumps(payload))
            data = self._recv_reset_response()
        except Exception:
            self._connect_ws()
            self.ws_client.send(json.dumps(payload))
            data = self._recv_reset_response()

        info_data = data.get("info", {})
        controllable_ids = info_data.get("controllableAgentIds", [])
        if not controllable_ids:
            # Fallback if single agent
            controlled_id = info_data.get("controlledPlayerId", "left_1")
            controllable_ids = [controlled_id]

        self.possible_agents = list(controllable_ids)
        self.agents = list(self.possible_agents)

        # Observations list from reset response
        raw_obs_list = data.get("observations", [])
        if not raw_obs_list and "observation" in data:
            raw_obs_list = [data["observation"]]

        observations: Dict[str, np.ndarray] = {}
        action_masks: Dict[str, np.ndarray] = {}
        for idx, agent in enumerate(self.agents):
            if idx < len(raw_obs_list):
                obs = np.array(raw_obs_list[idx], dtype=np.float32)
            else:
                obs = np.zeros(OBSERVATION_DIM, dtype=np.float32)
            observations[agent] = obs
            action_masks[agent] = np.ones(19, dtype=np.int8)

        infos: Dict[str, Any] = {agent: dict(info_data) for agent in self.agents}
        for agent in self.agents:
            infos[agent]["action_mask"] = action_masks[agent]
        return {agent: {"observation": observations[agent], "action_mask": action_masks[agent]} for agent in self.agents}, infos

    @staticmethod
    def _resolve_pending_pass_state(
        pending_pass: Optional[Dict[str, Any]],
        ball_owner_agent_idx: int,
        current_ev_type: Optional[str],
        agents: List[str],
    ) -> Tuple[List[Dict[str, Any]], Optional[Dict[str, Any]]]:
        """
        Stateless pending-pass resolution. Returns (resolution_events, new_pending_pass).
        Used by both the single-env step() and the batched step_batch() path.
        """
        events: List[Dict[str, Any]] = []

        # A new pass attempt while one is pending: clear the stale pending
        # pass; the engine's explicit pass_completed / pass_intercepted events
        # (Phase 11) are the authoritative source of truth.
        if current_ev_type == "pass" and pending_pass is not None:
            pending_pass = None

        if pending_pass is not None:
            pending_pass["age"] += 1
            resolved_type: Optional[str] = None
            if 0 <= ball_owner_agent_idx < len(agents):
                owner_id = agents[ball_owner_agent_idx]
                if owner_id != pending_pass["agent_id"]:
                    resolved_type = (
                        "PASS_FAILED" if owner_id.startswith("right_") else "PASS_COMPLETED"
                    )
            elif current_ev_type in ("interception", "tackle", "foul", "out_of_bounds", "offside", "pass_intercepted"):
                resolved_type = "PASS_FAILED"
            if resolved_type is None and pending_pass["age"] > 60:
                resolved_type = "PASS_FAILED"
            if resolved_type is not None:
                events.append(
                    {
                        "type": resolved_type,
                        "team": "left",
                        "agent_id": pending_pass["agent_id"],
                    }
                )
                pending_pass = None

        if current_ev_type == "pass" and pending_pass is None:
            passer = (
                agents[ball_owner_agent_idx]
                if 0 <= ball_owner_agent_idx < len(agents)
                else None
            )
            pending_pass = {"agent_id": passer, "age": 0}

        return events, pending_pass

    def _resolve_pending_pass(
        self,
        ball_owner_agent_idx: int,
        current_ev_type: Optional[str],
    ) -> List[Dict[str, Any]]:
        """Legacy single-env wrapper around _resolve_pending_pass_state."""
        events, self._pending_pass = GMNMultiAgentEnv._resolve_pending_pass_state(
            self._pending_pass, ball_owner_agent_idx, current_ev_type, self.agents
        )
        return events

    @staticmethod
    def _build_shaper_events(
        event_code: int,
        score_l: int,
        score_r: int,
        agents: List[str],
        ball_owner_agent_idx: int,
    ) -> List[Dict[str, Any]]:
        """Map a binary frame event_code to shaper-consumable step_events."""
        step_events: List[Dict[str, Any]] = []
        if 0 < event_code < len(EVENT_CODE_MAP):
            ev_type = EVENT_CODE_MAP[event_code]
            if ev_type:
                shaper_type = None
                shaper_team = "left"
                if ev_type == "pass":
                    shaper_type = None
                elif ev_type == "shot":
                    shaper_type = "SHOT_TAKEN"
                elif ev_type == "shot_saved":
                    shaper_type = "SHOT_SAVED"
                elif ev_type == "shot_missed":
                    shaper_type = "SHOT_MISSED"
                elif ev_type == "goal":
                    shaper_type = "GOAL_SCORED"
                    shaper_team = "left" if score_l > 0 else "right"
                elif ev_type in ("interception", "tackle", "foul"):
                    shaper_type = "TURNOVER_CONCEDED"
                    shaper_team = "right"
                elif ev_type == "pass_completed":
                    shaper_type = "PASS_COMPLETED"
                    shaper_team = "left"
                elif ev_type == "pass_intercepted":
                    shaper_type = "PASS_INTERCEPTED"
                    shaper_team = "right"

                if shaper_type is not None:
                    event_dict: Dict[str, Any] = {"type": shaper_type, "team": shaper_team}
                    if 0 <= ball_owner_agent_idx < len(agents):
                        event_dict["agent_id"] = agents[ball_owner_agent_idx]
                    step_events.append(event_dict)
        return step_events

    @staticmethod
    def _apply_shaping_for_env(
        env_state: Dict[str, Any],
        shared_reward: float,
        shared_term: bool,
        shared_trunc: bool,
        event_code: int,
        ball_owner_agent_idx: int,
        score_l: int,
        score_r: int,
        actions: Dict[str, int],
    ) -> Dict[str, float]:
        """M5: Apply cooperative reward shaping for one sub-environment."""
        shaper = env_state.get("reward_shaper")
        if shaper is None:
            return {}

        current_ev_type = EVENT_CODE_MAP[event_code] if 0 < event_code < len(EVENT_CODE_MAP) else None
        agents = env_state["agents"]

        # Build step_events from the frame's event_code.
        step_events = GMNMultiAgentEnv._build_shaper_events(event_code, score_l, score_r, agents, ball_owner_agent_idx)

        # Resolve pending pass for this sub-env.
        resolution_events, env_state["pending_pass"] = GMNMultiAgentEnv._resolve_pending_pass_state(
            env_state.get("pending_pass"), ball_owner_agent_idx, current_ev_type, agents
        )
        step_events = resolution_events + step_events

        # Store actions for shot-attribution fallback.
        env_state["last_actions"] = actions

        current_ball_owner = None
        if 0 <= ball_owner_agent_idx < len(agents):
            agent_id = agents[ball_owner_agent_idx]
            team = "left" if not agent_id.startswith("right_") else "right"
            current_ball_owner = {"agent_id": agent_id, "team": team}

        try:
            return shaper.compute_shaped_rewards(
                base_rewards={a: shared_reward for a in agents},
                step_events=step_events,
                info_ground_truth={"current_ball_owner": current_ball_owner},
                active_agents=list(agents),
                actions=actions,
            )
        except Exception:
            return {}

    def step(
        self,
        actions: Dict[str, int],
    ) -> Tuple[
        Dict[str, np.ndarray],
        Dict[str, float],
        Dict[str, bool],
        Dict[str, bool],
        Dict[str, Any],
    ]:
        """
        Executes a multi-agent joint action step.
        actions: mapping from agent ID to discrete action (0..18).
        """
        # Batched mode: delegate to step_batch for all sub-environments and
        # return only the first sub-env's result through the standard contract.
        if self.batch_size > 1:
            batch_results = self.step_batch([actions])
            if not batch_results:
                return {}, {}, {}, {}, {}
            return batch_results[0]

        if not self.agents:
            return {}, {}, {}, {}, {}

        self._step_count += 1
        num_agents = len(self.agents)

        # Pack actions strictly in self.agents (controllableAgentIds) order
        action_bytes = bytearray(num_agents)
        for i, agent in enumerate(self.agents):
            act = int(actions.get(agent, 0))
            if not (0 <= act < ACTION_SPACE_SIZE):
                raise ValueError(
                    f"[GMN-PettingZoo] Invalid action {act} for agent {agent}. Must be in [0, {ACTION_SPACE_SIZE - 1}]."
                )
            action_bytes[i] = act

        if self.ws_client is None:
            self._connect_ws()

        try:
            self.ws_client.send(bytes(action_bytes))
            data, episode_stats, defender_reward, reward_components = self._recv_step_response(num_agents)
        except Exception as e:
            # Log bridge errors for forensic debugging
            if getattr(self, "_forensic_debug", False):
                import sys as _sys
                print(
                    f"[FORENSIC_BRIDGE_ERROR]\n"
                    f"scenario={self.scenario}\n"
                    f"episode={getattr(self, '_episode_index', -1)}\n"
                    f"global_step={self._step_count}\n"
                    f"error_type={type(e).__name__}\n"
                    f"error_message={str(e)}\n"
                    f"bridge_error_count={getattr(self, '_bridge_error_count', 0)}\n"
                    f"[END_FORENSIC_BRIDGE_ERROR]",
                    flush=True,
                    file=_sys.stderr,
                )
            self._connect_ws()
            self.ws_client.send(bytes(action_bytes))
            data, episode_stats, defender_reward, reward_components = self._recv_step_response(num_agents)

        if isinstance(data, str):
            raise RuntimeError(f"[GMN-PettingZoo] Bridge sent text error: {data}")
        if not isinstance(data, (bytes, bytearray)):
            raise RuntimeError(f"[GMN-PettingZoo] Expected binary WebSocket frame, got {type(data)}")

        obs_bytes = OBSERVATION_DIM * 4
        is_rondo = self.scenario == "academy_rondo_4v1"
        header_size = 22 if is_rondo else 18
        mask_bytes = 19
        expected_len = header_size + obs_bytes * num_agents + mask_bytes * num_agents
        if len(data) != expected_len:
            raise RuntimeError(
                f"[GMN-PettingZoo Frame Length Error] Expected {expected_len} bytes "
                f"({header_size}B header + {obs_bytes}B * {num_agents} agents + {mask_bytes}B * {num_agents} masks), but received {len(data)} bytes."
            )

        # Unpack header
        reward, term, trunc, score_l, score_r, cp_reward, dist_goal, event_code, ball_owner_agent_idx = struct.unpack_from(
            "<f??BBffBB", data, 0
        )

        # Bridge error-frame sentinel (P0 #5): surface loudly instead of silently
        # accumulating a -999 penalty into episode reward.
        if float(reward) <= -998.0 and bool(term):
            self._bridge_error_count += 1
            raise RuntimeError(
                "[GMN-PettingZoo Bridge Error] Bridge returned an error frame "
                "(reward <= -998.0, terminated=true). This indicates an internal "
                "bridge error (e.g., invalid action, engine exception, or WebSocket "
                "failure). Check the bridge server logs for the root cause."
            )

        # For rondo scenarios, the bridge sends a split reward: attacker reward in the
        # standard reward field, and a separate defenderReward at offset 18
        # (observations start at 22).
        if is_rondo:
            defender_reward = struct.unpack_from("<f", data, 18)[0]

        shared_reward = float(reward)
        shared_term = bool(term)
        shared_trunc = bool(trunc)

        # Step 2/3 provenance: capture raw binary-frame values on every tick.
        # On terminal ticks these are the exact values that entered the pipeline.
        self._last_frame_reward = float(reward)
        self._last_frame_event_code = int(event_code)
        self._last_frame_score = {"left": int(score_l), "right": int(score_r)}
        self._last_shared_reward = shared_reward

        shared_info: Dict[str, Any] = {
            "score": {"left": int(score_l), "right": int(score_r)},
            "checkpointReward": float(cp_reward),
            "ballDistanceToGoal": float(dist_goal),
            "eventCode": int(event_code),
            "frame_length": len(data),
            "step": self._step_count,
        }
        if 0 < event_code < len(EVENT_CODE_MAP):
            ev_type = EVENT_CODE_MAP[event_code]
            if ev_type:
                shared_info["event"] = {"type": ev_type}

        # Attach ground-truth engine stats if the bridge sent them on episode end.
        # Include both termination (goal/scenario_complete) and truncation (clock expiry)
        # so pass/shot accuracy is computed for all episode endings, not just goals.
        if episode_stats and (shared_term or shared_trunc):
            shared_info["ground_truth"] = {
                "possession_left_pct": episode_stats.get("possession_left_pct"),
                "completed_passes_left": episode_stats.get("completed_passes_left"),
                "attempted_passes_left": episode_stats.get("attempted_passes_left"),
                "shots_on_target_left": episode_stats.get("shots_on_target_left"),
                "total_shots_left": episode_stats.get("total_shots_left"),
                "pass_accuracy": (
                    episode_stats.get("completed_passes_left", 0) / episode_stats.get("attempted_passes_left", 1)
                    if episode_stats.get("attempted_passes_left", 0) > 0
                    else 0.0
                ),
                "shot_accuracy": (
                    episode_stats.get("shots_on_target_left", 0) / episode_stats.get("total_shots_left", 1)
                    if episode_stats.get("total_shots_left", 0) > 0
                    else 0.0
                ),
                "current_ball_owner": episode_stats.get("current_ball_owner"),
            }

        # Standardized evaluator metrics: expose episode lengths on termination.
        if shared_term or shared_trunc:
            shared_info["episode_length_steps"] = self._step_count
            shared_info["episode_physics_ticks"] = self._step_count

        # Parse action masks (19 bytes per agent, after observations)
        mask_offset = header_size + num_agents * obs_bytes
        action_masks: Dict[str, np.ndarray] = {}
        for i, agent in enumerate(self.agents):
            agent_mask_offset = mask_offset + i * 19
            mask = np.frombuffer(data, dtype="<u1", count=19, offset=agent_mask_offset).copy().astype(np.int8)
            action_masks[agent] = mask

        # Build per-step step_events for reward shaping from the single event_code
        step_events: List[Dict[str, Any]] = []
        if 0 < event_code < len(EVENT_CODE_MAP):
            ev_type = EVENT_CODE_MAP[event_code]
            if ev_type:
                # Map engine event types to shaper-consumable event types.
                # Engine emits: pass, shot, shot_saved, shot_missed, goal,
                # interception, tackle, foul, kickoff, out_of_bounds,
                # scenario_complete, scenario_failed, offside
                # Shaper expects: PASS_COMPLETED, PASS_FAILED, TURNOVER_CONCEDED,
                # SHOT_TAKEN, GOAL_SCORED
                shaper_type = None
                shaper_team = "left"
                if ev_type == "pass":
                    # Engine emits "pass" at initiation. Do NOT credit a completed
                    # pass here; _resolve_pending_pass() finalizes it when a
                    # teammate gains possession (or it fails / times out).
                    shaper_type = None
                elif ev_type == "shot":
                    shaper_type = "SHOT_TAKEN"
                elif ev_type == "shot_saved":
                    shaper_type = "SHOT_SAVED"
                elif ev_type == "shot_missed":
                    shaper_type = "SHOT_MISSED"
                elif ev_type == "goal":
                    shaper_type = "GOAL_SCORED"
                    shaper_team = "left" if score_l > 0 else "right"
                elif ev_type in ("interception", "tackle", "foul"):
                    shaper_type = "TURNOVER_CONCEDED"
                    shaper_team = "right"
                elif ev_type == "pass_completed":
                    shaper_type = "PASS_COMPLETED"
                    shaper_team = "left"
                elif ev_type == "pass_intercepted":
                    shaper_type = "PASS_INTERCEPTED"
                    shaper_team = "right"

                if shaper_type is not None:
                    event_dict: Dict[str, Any] = {"type": shaper_type, "team": shaper_team}
                    # Attach agent_id if ball owner is a controllable agent
                    if 0 <= ball_owner_agent_idx < len(self.agents):
                        event_dict["agent_id"] = self.agents[ball_owner_agent_idx]
                    step_events.append(event_dict)

        # Resolve the pending pass (state machine over possession) and prepend the
        # resolution so a completed pass is credited before a same-step SHOT_TAKEN
        # (keeps chain-aware shaping ordering correct).
        if self.enable_reward_shaping and self.reward_shaper is not None:
            current_ev_type = (
                EVENT_CODE_MAP[event_code] if 0 < event_code < len(EVENT_CODE_MAP) else None
            )
            step_events = (
                self._resolve_pending_pass(ball_owner_agent_idx, current_ev_type) + step_events
            )

        observations: Dict[str, np.ndarray] = {}
        rewards: Dict[str, float] = {}
        terminations: Dict[str, bool] = {}
        truncations: Dict[str, bool] = {}
        infos: Dict[str, Any] = {}

        for i, agent in enumerate(self.agents):
            offset = header_size + i * obs_bytes
            obs = np.frombuffer(data, dtype="<f4", count=OBSERVATION_DIM, offset=offset).copy()
            # Rondo: assign team-specific rewards; non-rondo keeps the shared broadcast.
            if is_rondo:
                rewards[agent] = defender_reward if agent.startswith("right_") else shared_reward
            else:
                rewards[agent] = shared_reward
            terminations[agent] = shared_term
            truncations[agent] = shared_trunc
            infos[agent] = dict(shared_info)
            infos[agent]["action_mask"] = action_masks[agent]
            observations[agent] = {
                "observation": obs,
                "action_mask": action_masks[agent],
            }
            if step_events:
                infos[agent]["step_events"] = step_events

        # Collect debug reward components if enabled
        if self.debug_rewards and reward_components is not None:
            self.reward_components.append({
                "step": self._step_count,
                "components": reward_components,
                "shared_reward": shared_reward,
                "event_code": int(event_code),
            })

        # Apply cooperative reward shaping if enabled.
        # NOTE: reward shaper must run on terminal steps too, because its internal
        # cumulative counters (goals, passes, turnovers) are side effects of
        # compute_shaped_rewards(). Skipping it on terminal steps makes the
        # live-training event counters blind to any goal scored on the final tick.
        if self.enable_reward_shaping and self.reward_shaper is not None:
            try:
                # Derive current ball owner from binary frame ballOwnerAgentId
                current_ball_owner = None
                if 0 <= ball_owner_agent_idx < len(self.agents):
                    agent_id = self.agents[ball_owner_agent_idx]
                    team = "left"
                    if agent_id.startswith("right_"):
                        team = "right"
                    current_ball_owner = {"agent_id": agent_id, "team": team}

                shaped_rewards = self.reward_shaper.compute_shaped_rewards(
                    base_rewards=rewards,
                    step_events=step_events,
                    info_ground_truth={"current_ball_owner": current_ball_owner},
                    active_agents=list(self.agents),
                    actions=actions,
                )
                # M2: Always apply shaped rewards, including on terminal steps.
                # The engine's raw reward (e.g. +2.00 goal signal) is already in
                # `rewards[agent]`; the shaper adds cooperative bonuses on top.
                # Skipping on terminal steps caused goal bonuses and assisted-goal
                # bonuses to be silently dropped.
                for agent in self.agents:
                    if agent in shaped_rewards:
                        rewards[agent] = shaped_rewards[agent]
            except Exception as e:
                logger.debug(f"Reward shaping skipped due to error: {e}")

        # Phase 2: FORENSIC_ENV_TERMINAL capture
        if getattr(self, "_forensic_debug", False) and (shared_term or shared_trunc):
            shaping_applied = (
                self.enable_reward_shaping
                and self.reward_shaper is not None
                and not shared_term
                and not shared_trunc
            )
            print(
                f"[FORENSIC_ENV_TERMINAL]\n"
                f"scenario={self.scenario}\n"
                f"episode={self._episode_index}\n"
                f"global_step={self._step_count}\n"
                f"\n"
                f"parser_reward={float(reward)}\n"
                f"env_reward={shared_reward}\n"
                f"\n"
                f"terminated_any={shared_term}\n"
                f"truncated_any={shared_trunc}\n"
                f"\n"
                f"agents={list(self.agents)}\n"
                f"agent_rewards={rewards}\n"
                f"\n"
                f"shared_reward={shared_reward}\n"
                f"\n"
                f"reward_shaper_enabled={self.enable_reward_shaping}\n"
                f"reward_shaper_skipped={not shaping_applied}\n"
                f"\n"
                f"score_left={score_l}\n"
                f"score_right={score_r}\n"
                f"event_code={event_code}\n"
                f"ball_owner_agent_idx={ball_owner_agent_idx}\n"
                f"[END_FORENSIC_ENV_TERMINAL]",
                flush=True,
            )

        if shared_term or shared_trunc:
            self.agents = []

        return observations, rewards, terminations, truncations, infos

    def render(self):
        """Render mode placeholder."""
        if self.render_mode == "human":
            print(f"[GMNMultiAgentEnv] Step: {self._step_count} | Agents: {self.possible_agents}")

    def close(self):
        """Cleans up WebSocket connection and bridge subprocess."""
        if self.ws_client is not None:
            try:
                self.ws_client.send(json.dumps({"type": "close"}))
                self.ws_client.close()
            except Exception:
                pass
            self.ws_client = None

        if self.bridge_process is not None:
            try:
                self.bridge_process.terminate()
                self.bridge_process.wait(timeout=2.0)
            except Exception:
                pass
            self.bridge_process = None

    def __getstate__(self):
        """Allows pickling by excluding unpicklable socket/process references."""
        state = self.__dict__.copy()
        state["ws_client"] = None
        state["bridge_process"] = None
        return state

    def __setstate__(self, state):
        """Restores state from pickle and marks client/process for lazy re-initialization."""
        self.__dict__.update(state)
        self.bridge_process = None
        self.ws_client = None
        self._needs_bridge = True
