#!/usr/bin/env python3
"""
GMN-Football-3 — Python Contract Constants Synchronizer
Reads src/engine/Contract.ts and synchronizes Python environments to eliminate configuration drift.
"""

import os
import re
import sys

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CONTRACT_TS = os.path.join(ROOT_DIR, "src", "engine", "Contract.ts")
GMN_GYM_PY = os.path.join(ROOT_DIR, "training", "gmn_gym.py")
GMN_PETTINGZOO_PY = os.path.join(ROOT_DIR, "training", "gmn_pettingzoo.py")
CHECKPOINT_CONTRACT_PY = os.path.join(ROOT_DIR, "training", "checkpoint_contract.py")


def sync_contracts():
    if not os.path.exists(CONTRACT_TS):
        print(f"Error: Contract.ts not found at {CONTRACT_TS}")
        sys.exit(1)

    with open(CONTRACT_TS, "r", encoding="utf-8") as f:
        ts_content = f.read()

    env_version = re.search(r"export const GMN_ENV_VERSION\s*=\s*['\"]([^'\"]+)['\"]", ts_content).group(1)
    obs_schema = re.search(r"export const OBSERVATION_SCHEMA_VERSION\s*=\s*['\"]([^'\"]+)['\"]", ts_content).group(1)
    act_schema = re.search(r"export const ACTION_SCHEMA_VERSION\s*=\s*['\"]([^'\"]+)['\"]", ts_content).group(1)
    role_dim = int(re.search(r"export const ROLE_DIM\s*=\s*(\d+)", ts_content).group(1))
    base_obs_dim = int(re.search(r"export const BASE_OBSERVATION_DIM\s*=\s*(\d+)", ts_content).group(1))
    act_space = int(re.search(r"export const ACTION_SPACE_SIZE\s*=\s*(\d+)", ts_content).group(1))
    obs_dim = base_obs_dim + role_dim

    role_vocab_match = re.search(r"export const ROLE_VOCABULARY\s*=\s*\[([\s\S]*?)\]\s*as const;", ts_content)
    roles = re.findall(r"['\"]([^'\"]+)['\"]", role_vocab_match.group(1))

    event_map_match = re.search(r"export const EVENT_CODE_MAP\s*=\s*\[([\s\S]*?)\]\s*as const;", ts_content)
    event_items = [s.strip() for s in event_map_match.group(1).split(",") if s.strip()]
    event_lines = []
    for item in event_items:
        if item in ("undefined", "null"):
            event_lines.append("    None,")
        else:
            m = re.search(r"['\"]([^'\"]+)['\"]", item)
            if m:
                event_lines.append(f'    "{m.group(1)}",')

    roles_str = ", ".join(f'"{r}"' for r in roles)
    events_str = "\n".join(event_lines)

    py_block = f"""# --- AUTOGENERATED CONTRACT CONSTANTS (DO NOT EDIT DIRECTLY) ---
# Generated from src/engine/Contract.ts by scripts/sync_contracts.ts
GMN_ENV_VERSION = "{env_version}"
OBSERVATION_SCHEMA_VERSION = "{obs_schema}"
ACTION_SCHEMA_VERSION = "{act_schema}"

ROLE_VOCABULARY = [{roles_str}]
ROLE_DIM = {role_dim}
BASE_OBSERVATION_DIM = {base_obs_dim}
OBSERVATION_DIM = {obs_dim}
ACTION_SPACE_SIZE = {act_space}

EVENT_CODE_MAP = [
{events_str}
]
# --- END AUTOGENERATED CONTRACT CONSTANTS ---"""

    start_marker = "# --- AUTOGENERATED CONTRACT CONSTANTS (DO NOT EDIT DIRECTLY) ---"
    end_marker = "# --- END AUTOGENERATED CONTRACT CONSTANTS ---"

    for target in [GMN_GYM_PY, GMN_PETTINGZOO_PY, CHECKPOINT_CONTRACT_PY]:
        if not os.path.exists(target):
            continue
        with open(target, "r", encoding="utf-8") as f:
            content = f.read()

        if start_marker in content and end_marker in content:
            pattern = re.compile(f"{re.escape(start_marker)}[\\s\\S]*?{re.escape(end_marker)}", re.MULTILINE)
            content = pattern.sub(py_block, content)
        else:
            content = f"{py_block}\n\n{content}"

        with open(target, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✓ Python synchronizer updated: {os.path.relpath(target, ROOT_DIR)}")


if __name__ == "__main__":
    sync_contracts()
