import { ScenarioConfig } from '../types/football';

export const ACADEMY_SCENARIOS: ScenarioConfig[] = [
  {
    id: 'academy_empty_goal',
    stage: 1,
    name: 'Academy: Empty Goal',
    codeName: 'academy_empty_goal',
    description: 'Learn fundamental forward movement, ball control, and shooting into an open goal.',
    instructions: 'Control Player #10, advance with the ball, and shoot [K] into the empty net.',
    difficulty: 'Beginner',
    teamLeftPlayers: 1,
    teamRightPlayers: 0,
    hasGoalkeeperLeft: false,
    hasGoalkeeperRight: false,
    timeLimitSeconds: 15,
    setup: {
      ball: { x: 0.5, y: 0, z: 0 },
      leftPlayers: [
        { role: 'ST', pos: { x: 0.45, y: 0 }, isControlled: true },
      ],
      rightPlayers: [],
      positionJitter: 0.03,
    },
    objectives: [
      { id: 'score_goal', text: 'Score a goal into the opponent net', isCompleted: false, isFailed: false },
      { id: 'within_time', text: 'Score within 15 seconds', isCompleted: false, isFailed: false },
    ],
    terminateOnOpponentPossession: true,
    rewards: {
      scoring: 1.0,
      completion: 100,
    },
  },
  {
    id: 'academy_run_to_score',
    stage: 2,
    name: 'Academy: Run to Score',
    codeName: 'academy_run_to_score',
    description: 'Sprint past a chasing defender, maintain possession, and beat the goalkeeper.',
    instructions: 'Sprint [Shift] toward the penalty box, evade the defender chasing from behind, and score [K].',
    difficulty: 'Beginner',
    teamLeftPlayers: 1,
    teamRightPlayers: 2,
    hasGoalkeeperLeft: false,
    hasGoalkeeperRight: true,
    timeLimitSeconds: 20,
    setup: {
      ball: { x: 0.2, y: 0.05, z: 0 },
      leftPlayers: [
        { role: 'ST', pos: { x: 0.15, y: 0.05 }, isControlled: true },
      ],
      rightPlayers: [
        { role: 'GK', pos: { x: 0.95, y: 0 } },
        { role: 'CB', pos: { x: 0.0, y: -0.08 } }, // Chasing defender
      ],
      positionJitter: 0.04,
    },
    objectives: [
      { id: 'score_goal', text: 'Score past the goalkeeper', isCompleted: false, isFailed: false },
      { id: 'avoid_dispossess', text: 'Do not lose ball possession to the defender', isCompleted: false, isFailed: false },
    ],
    terminateOnOpponentPossession: true,
    rewards: {
      scoring: 1.0,
      completion: 200,
    },
  },
  {
    id: 'academy_pass_and_shoot_with_keeper',
    stage: 3,
    name: 'Academy: Pass & Shoot with Keeper',
    codeName: 'academy_pass_and_shoot_with_keeper',
    description: 'Execute a 2-player passing combination to pull the goalkeeper out and score.',
    instructions: 'Pass [J] to your open teammate to pull the goalkeeper off his line, then finish into the open corner.',
    difficulty: 'Intermediate',
    teamLeftPlayers: 2,
    teamRightPlayers: 2,
    hasGoalkeeperLeft: false,
    hasGoalkeeperRight: true,
    timeLimitSeconds: 25,
    setup: {
      ball: { x: 0.4, y: -0.15, z: 0 },
      leftPlayers: [
        { role: 'LW', pos: { x: 0.35, y: -0.15 }, isControlled: true },
        { role: 'ST', pos: { x: 0.55, y: 0.18 } },
      ],
      rightPlayers: [
        { role: 'GK', pos: { x: 0.95, y: 0 } },
        { role: 'CB', pos: { x: 0.65, y: -0.05 } },
      ],
      positionJitter: 0.04,
    },
    objectives: [
      { id: 'complete_pass', text: 'Complete at least one pass [J]', isCompleted: false, isFailed: false },
      { id: 'score_goal', text: 'Score a goal', isCompleted: false, isFailed: false },
    ],
    terminateOnOpponentPossession: true,
    rewards: {
      scoring: 1.0,
      completion: 350,
    },
  },
  {
    id: 'academy_3_vs_1_with_keeper',
    stage: 4,
    name: 'Academy: 3 vs 1 with Keeper',
    codeName: 'academy_3_vs_1_with_keeper',
    description: 'Form passing triangles to break down a resilient defender and beat the keeper.',
    instructions: 'Use quick 1-2 passes [J] and lobs [L] to create space around the defender and score cleanly.',
    difficulty: 'Intermediate',
    teamLeftPlayers: 3,
    teamRightPlayers: 2,
    hasGoalkeeperLeft: false,
    hasGoalkeeperRight: true,
    timeLimitSeconds: 30,
    setup: {
      ball: { x: 0.25, y: 0, z: 0 },
      leftPlayers: [
        { role: 'CAM', pos: { x: 0.2, y: 0 }, isControlled: true },
        { role: 'LW', pos: { x: 0.45, y: -0.22 } },
        { role: 'RW', pos: { x: 0.45, y: 0.22 } },
      ],
      rightPlayers: [
        { role: 'GK', pos: { x: 0.95, y: 0 } },
        { role: 'CB', pos: { x: 0.55, y: 0 } },
      ],
      positionJitter: 0.05,
    },
    objectives: [
      { id: 'create_triangle', text: 'Connect 2+ passes without losing possession', isCompleted: false, isFailed: false },
      { id: 'score_goal', text: 'Score past the goalkeeper', isCompleted: false, isFailed: false },
    ],
    terminateOnOpponentPossession: true,
    rewards: {
      scoring: 1.0,
      completion: 500,
    },
  },
  {
    id: 'academy_3_vs_1_defender_2',
    stage: 4,
    name: 'Academy: 3 vs 2 with Keeper (Variation)',
    codeName: 'academy_3_vs_1_defender_2',
    description: '3v2 variation with an extra central defender on the right team.',
    instructions: 'Evaluate multi-agent policy against a dual-defender formation.',
    difficulty: 'Advanced',
    teamLeftPlayers: 3,
    teamRightPlayers: 3,
    hasGoalkeeperLeft: false,
    hasGoalkeeperRight: true,
    timeLimitSeconds: 30,
    setup: {
      ball: { x: 0.25, y: 0, z: 0 },
      leftPlayers: [
        { role: 'CAM', pos: { x: 0.2, y: 0 }, isControlled: true },
        { role: 'LW', pos: { x: 0.45, y: -0.22 } },
        { role: 'RW', pos: { x: 0.45, y: 0.22 } },
      ],
      rightPlayers: [
        { role: 'GK', pos: { x: 0.95, y: 0 } },
        { role: 'CB', pos: { x: 0.55, y: -0.12 } },
        { role: 'CB', pos: { x: 0.62, y: 0.12 } },
      ],
      positionJitter: 0.05,
    },
    objectives: [
      { id: 'score_goal', text: 'Score past two defenders and goalkeeper', isCompleted: false, isFailed: false },
    ],
    terminateOnOpponentPossession: true,
    rewards: {
      scoring: 1.0,
      completion: 500,
    },
  },
  {
    id: 'academy_3_vs_1_defender_3',
    stage: 4,
    name: 'Academy: 3 vs 3 with Keeper (Variation)',
    codeName: 'academy_3_vs_1_defender_3',
    description: '3v3 variation with three right-team defenders protecting the penalty area.',
    instructions: 'Evaluate multi-agent policy against a triple-defender low block.',
    difficulty: 'Master',
    teamLeftPlayers: 3,
    teamRightPlayers: 4,
    hasGoalkeeperLeft: false,
    hasGoalkeeperRight: true,
    timeLimitSeconds: 30,
    setup: {
      ball: { x: 0.25, y: 0, z: 0 },
      leftPlayers: [
        { role: 'CAM', pos: { x: 0.2, y: 0 }, isControlled: true },
        { role: 'LW', pos: { x: 0.45, y: -0.22 } },
        { role: 'RW', pos: { x: 0.45, y: 0.22 } },
      ],
      rightPlayers: [
        { role: 'GK', pos: { x: 0.95, y: 0 } },
        { role: 'CB', pos: { x: 0.52, y: -0.16 } },
        { role: 'CB', pos: { x: 0.52, y: 0.16 } },
        { role: 'CB', pos: { x: 0.68, y: 0.0 } },
      ],
      positionJitter: 0.05,
    },
    objectives: [
      { id: 'score_goal', text: 'Score past three defenders and goalkeeper', isCompleted: false, isFailed: false },
    ],
    terminateOnOpponentPossession: true,
    rewards: {
      scoring: 1.0,
      completion: 500,
    },
  },
  {
    id: 'academy_3_vs_1_keeper_aggressive',
    stage: 4,
    name: 'Academy: 3 vs 1 Aggressive Keeper (Variation)',
    codeName: 'academy_3_vs_1_keeper_aggressive',
    description: '3v1 variation with sweeper-keeper positioning higher up the pitch.',
    instructions: 'Evaluate multi-agent policy against an assertive, rushing goalkeeper.',
    difficulty: 'Advanced',
    teamLeftPlayers: 3,
    teamRightPlayers: 2,
    hasGoalkeeperLeft: false,
    hasGoalkeeperRight: true,
    timeLimitSeconds: 30,
    setup: {
      ball: { x: 0.25, y: 0, z: 0 },
      leftPlayers: [
        { role: 'CAM', pos: { x: 0.2, y: 0 }, isControlled: true },
        { role: 'LW', pos: { x: 0.45, y: -0.22 } },
        { role: 'RW', pos: { x: 0.45, y: 0.22 } },
      ],
      rightPlayers: [
        { role: 'GK', pos: { x: 0.82, y: 0 } },
        { role: 'CB', pos: { x: 0.55, y: 0 } },
      ],
      positionJitter: 0.05,
    },
    objectives: [
      { id: 'score_goal', text: 'Score past aggressive goalkeeper', isCompleted: false, isFailed: false },
    ],
    terminateOnOpponentPossession: true,
    rewards: {
      scoring: 1.0,
      completion: 500,
    },
  },
  {
    id: 'academy_3_vs_1_shifted',
    stage: 4,
    name: 'Academy: 3 vs 1 Shifted Arrangement (Variation)',
    codeName: 'academy_3_vs_1_shifted',
    description: '3v1 variation with asymmetric defender positioning.',
    instructions: 'Evaluate multi-agent policy against an offset defensive alignment.',
    difficulty: 'Intermediate',
    teamLeftPlayers: 3,
    teamRightPlayers: 2,
    hasGoalkeeperLeft: false,
    hasGoalkeeperRight: true,
    timeLimitSeconds: 30,
    setup: {
      ball: { x: 0.25, y: -0.05, z: 0 },
      leftPlayers: [
        { role: 'CAM', pos: { x: 0.2, y: -0.05 }, isControlled: true },
        { role: 'LW', pos: { x: 0.45, y: -0.27 } },
        { role: 'RW', pos: { x: 0.45, y: 0.17 } },
      ],
      rightPlayers: [
        { role: 'GK', pos: { x: 0.93, y: -0.08 } },
        { role: 'CB', pos: { x: 0.42, y: 0.14 } },
      ],
      positionJitter: 0.05,
    },
    objectives: [
      { id: 'score_goal', text: 'Score past shifted defensive setup', isCompleted: false, isFailed: false },
    ],
    terminateOnOpponentPossession: true,
    rewards: {
      scoring: 1.0,
      completion: 500,
    },
  },
  {
    id: 'academy_3_vs_1_randomized',
    stage: 4,
    name: 'Academy: 3 vs 1 Randomized (Variation)',
    codeName: 'academy_3_vs_1_randomized',
    description: '3v1 variation with expanded position jitter across pitch coordinates.',
    instructions: 'Evaluate multi-agent policy robustness under wide initial perturbations.',
    difficulty: 'Intermediate',
    teamLeftPlayers: 3,
    teamRightPlayers: 2,
    hasGoalkeeperLeft: false,
    hasGoalkeeperRight: true,
    timeLimitSeconds: 30,
    setup: {
      ball: { x: 0.25, y: 0, z: 0 },
      leftPlayers: [
        { role: 'CAM', pos: { x: 0.2, y: 0 }, isControlled: true },
        { role: 'LW', pos: { x: 0.45, y: -0.22 } },
        { role: 'RW', pos: { x: 0.45, y: 0.22 } },
      ],
      rightPlayers: [
        { role: 'GK', pos: { x: 0.95, y: 0 } },
        { role: 'CB', pos: { x: 0.55, y: 0 } },
      ],
      positionJitter: 0.12,
    },
    objectives: [
      { id: 'score_goal', text: 'Score past defender and goalkeeper under random jitter', isCompleted: false, isFailed: false },
    ],
    terminateOnOpponentPossession: true,
    rewards: {
      scoring: 1.0,
      completion: 500,
    },
  },
  {
    id: '5_vs_5',
    stage: 5,
    name: '5 vs 5 Arena Match',
    codeName: '5_vs_5',
    description: 'Fast-paced small-sided competitive match with goalkeepers, corners, and fluid transitions.',
    instructions: 'Play a 5v5 match. Command your team or let AI policies battle in high-intensity football.',
    difficulty: 'Advanced',
    teamLeftPlayers: 5,
    teamRightPlayers: 5,
    hasGoalkeeperLeft: true,
    hasGoalkeeperRight: true,
    timeLimitSeconds: 90,
    setup: {
      ball: { x: 0, y: 0, z: 0 },
      leftPlayers: [
        { role: 'GK', pos: { x: -0.95, y: 0 } },
        { role: 'CB', pos: { x: -0.6, y: 0 } },
        { role: 'LM', pos: { x: -0.25, y: -0.2 } },
        { role: 'RM', pos: { x: -0.25, y: 0.2 } },
        { role: 'ST', pos: { x: -0.05, y: 0 }, isControlled: true },
      ],
      rightPlayers: [
        { role: 'GK', pos: { x: 0.95, y: 0 } },
        { role: 'CB', pos: { x: 0.6, y: 0 } },
        { role: 'LM', pos: { x: 0.25, y: 0.2 } },
        { role: 'RM', pos: { x: 0.25, y: -0.2 } },
        { role: 'ST', pos: { x: 0.05, y: 0 } },
      ],
    },
    objectives: [
      { id: 'win_match', text: 'Score more goals than the opponent', isCompleted: false, isFailed: false },
      { id: 'control_possession', text: 'Maintain > 50% possession', isCompleted: false, isFailed: false },
    ],
    terminateOnOpponentPossession: false,
    rewards: {
      scoring: 1.0,
      completion: 800,
    },
  },
  {
    id: '11_vs_11',
    stage: 6,
    name: '11 vs 11 Full Pitch Match',
    codeName: '11_vs_11',
    description: 'Full regulation football match on the full pitch with all tactical roles, formations, and stamina.',
    instructions: 'Full 11v11 match simulation. Switch players [E], build attacking play with passes [J, L], and strike [K].',
    difficulty: 'Master',
    teamLeftPlayers: 11,
    teamRightPlayers: 11,
    hasGoalkeeperLeft: true,
    hasGoalkeeperRight: true,
    timeLimitSeconds: 180,
    setup: {
      ball: { x: 0, y: 0, z: 0 },
      leftPlayers: [], // Dynamically generated by formation
      rightPlayers: [],
    },
    objectives: [
      { id: 'win_match', text: 'Win the full 11v11 match', isCompleted: false, isFailed: false },
      { id: 'clean_sheet', text: 'Keep a clean sheet (concede 0 goals)', isCompleted: false, isFailed: false },
    ],
    terminateOnOpponentPossession: false,
    rewards: {
      scoring: 1.0,
      completion: 1200,
    },
  },
];
