/**
 * GMN-Football-3 — Automated Contract Constants Synchronization
 *
 * Single source of truth is `src/engine/Contract.ts`.
 * This script parses `src/engine/Contract.ts` and synchronizes the contract constants
 * into Python environments (`training/gmn_gym.py`, `training/gmn_pettingzoo.py`, `training/checkpoint_contract.py`)
 * to eliminate manual synchronization errors and prevent configuration drift.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '..');

const CONTRACT_TS_PATH = path.join(ROOT_DIR, 'src', 'engine', 'Contract.ts');
const GMN_GYM_PATH = path.join(ROOT_DIR, 'training', 'gmn_gym.py');
const GMN_PETTINGZOO_PATH = path.join(ROOT_DIR, 'training', 'gmn_pettingzoo.py');
const CHECKPOINT_CONTRACT_PY_PATH = path.join(ROOT_DIR, 'training', 'checkpoint_contract.py');

interface ExtractedContract {
  envVersion: string;
  obsSchemaVersion: string;
  actionSchemaVersion: string;
  roleVocabulary: string[];
  roleDim: number;
  baseObsDim: number;
  obsDim: number;
  actionSpaceSize: number;
  eventCodeMap: (string | null)[];
}

export function parseContractTs(content: string): ExtractedContract {
  const getMatch = (regex: RegExp, label: string): string => {
    const match = content.match(regex);
    if (!match || !match[1]) {
      throw new Error(`Failed to extract ${label} from Contract.ts`);
    }
    return match[1].trim();
  };

  const envVersion = getMatch(/export const GMN_ENV_VERSION\s*=\s*['"]([^'"]+)['"]/, 'GMN_ENV_VERSION');
  const obsSchemaVersion = getMatch(/export const OBSERVATION_SCHEMA_VERSION\s*=\s*['"]([^'"]+)['"]/, 'OBSERVATION_SCHEMA_VERSION');
  const actionSchemaVersion = getMatch(/export const ACTION_SCHEMA_VERSION\s*=\s*['"]([^'"]+)['"]/, 'ACTION_SCHEMA_VERSION');

  const roleDimStr = getMatch(/export const ROLE_DIM\s*=\s*(\d+)/, 'ROLE_DIM');
  const baseObsDimStr = getMatch(/export const BASE_OBSERVATION_DIM\s*=\s*(\d+)/, 'BASE_OBSERVATION_DIM');
  const actionSpaceSizeStr = getMatch(/export const ACTION_SPACE_SIZE\s*=\s*(\d+)/, 'ACTION_SPACE_SIZE');

  const roleDim = parseInt(roleDimStr, 10);
  const baseObsDim = parseInt(baseObsDimStr, 10);
  const actionSpaceSize = parseInt(actionSpaceSizeStr, 10);
  const obsDim = baseObsDim + roleDim;

  // Extract ROLE_VOCABULARY
  const roleVocabMatch = content.match(/export const ROLE_VOCABULARY\s*=\s*\[([\s\S]*?)\]\s*as const;/);
  let roleVocabulary: string[] = [];
  if (roleVocabMatch && roleVocabMatch[1]) {
    roleVocabulary = Array.from(roleVocabMatch[1].matchAll(/['"]([^'"]+)['"]/g)).map((m) => m[1]);
  } else {
    throw new Error('Failed to parse ROLE_VOCABULARY');
  }

  // Extract EVENT_CODE_MAP
  const eventCodeMatch = content.match(/export const EVENT_CODE_MAP\s*=\s*\[([\s\S]*?)\]\s*as const;/);
  let eventCodeMap: (string | null)[] = [];
  if (eventCodeMatch && eventCodeMatch[1]) {
    const rawItems = eventCodeMatch[1].split(',').map((s) => s.trim()).filter(Boolean);
    eventCodeMap = rawItems.map((item) => {
      if (item === 'undefined' || item === 'null') return null;
      const m = item.match(/['"]([^'"]+)['"]/);
      return m ? m[1] : null;
    });
  } else {
    throw new Error('Failed to parse EVENT_CODE_MAP');
  }

  return {
    envVersion,
    obsSchemaVersion,
    actionSchemaVersion,
    roleVocabulary,
    roleDim,
    baseObsDim,
    obsDim,
    actionSpaceSize,
    eventCodeMap,
  };
}

export function generatePythonContractBlock(contract: ExtractedContract): string {
  const roleVocabPy = contract.roleVocabulary.map((r) => `"${r}"`).join(', ');
  const eventCodeLines = contract.eventCodeMap.map((e) => (e === null ? '    None,' : `    "${e}",`)).join('\n');

  return `# --- AUTOGENERATED CONTRACT CONSTANTS (DO NOT EDIT DIRECTLY) ---
# Generated from src/engine/Contract.ts by scripts/sync_contracts.ts
GMN_ENV_VERSION = "${contract.envVersion}"
OBSERVATION_SCHEMA_VERSION = "${contract.obsSchemaVersion}"
ACTION_SCHEMA_VERSION = "${contract.actionSchemaVersion}"

ROLE_VOCABULARY = [${roleVocabPy}]
ROLE_DIM = ${contract.roleDim}
BASE_OBSERVATION_DIM = ${contract.baseObsDim}
OBSERVATION_DIM = ${contract.obsDim}
ACTION_SPACE_SIZE = ${contract.actionSpaceSize}

EVENT_CODE_MAP = [
${eventCodeLines}
]
# --- END AUTOGENERATED CONTRACT CONSTANTS ---`;
}

function updatePythonFile(filePath: string, pyBlock: string): boolean {
  if (!fs.existsSync(filePath)) {
    console.warn(`[sync_contracts] Warning: File not found: ${filePath}`);
    return false;
  }

  let content = fs.readFileSync(filePath, 'utf-8');
  const startMarker = '# --- AUTOGENERATED CONTRACT CONSTANTS (DO NOT EDIT DIRECTLY) ---';
  const endMarker = '# --- END AUTOGENERATED CONTRACT CONSTANTS ---';

  if (content.includes(startMarker) && content.includes(endMarker)) {
    const regex = new RegExp(`${escapeRegExp(startMarker)}[\\s\\S]*?${escapeRegExp(endMarker)}`, 'm');
    content = content.replace(regex, pyBlock);
  } else {
    // If markers don't exist yet, insert after imports or at top
    const topImportRegex = /^(import[\s\S]*?(?=\n\n|\n[A-Z_a-z]))/m;
    if (topImportRegex.test(content)) {
      content = content.replace(topImportRegex, `$1\n\n${pyBlock}`);
    } else {
      content = `${pyBlock}\n\n${content}`;
    }
  }

  fs.writeFileSync(filePath, content, 'utf-8');
  console.log(`✓ Synchronized contract constants into: ${path.relative(ROOT_DIR, filePath)}`);
  return true;
}

function escapeRegExp(string: string): string {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export function syncContracts(): void {
  console.log('==================================================');
  console.log('GMN-FOOTBALL-3 — CONTRACT CONSTANTS SYNCHRONIZER');
  console.log(`Source: ${path.relative(ROOT_DIR, CONTRACT_TS_PATH)}`);
  console.log('==================================================');

  const tsContent = fs.readFileSync(CONTRACT_TS_PATH, 'utf-8');
  const contract = parseContractTs(tsContent);

  console.log(`Parsed Environment Version:       ${contract.envVersion}`);
  console.log(`Observation Schema:               ${contract.obsSchemaVersion} (${contract.obsDim} floats: ${contract.baseObsDim} base + ${contract.roleDim} roles)`);
  console.log(`Action Schema:                    ${contract.actionSchemaVersion} (${contract.actionSpaceSize} discrete actions)`);
  console.log(`Role Vocabulary (${contract.roleVocabulary.length}):           ${contract.roleVocabulary.join(', ')}`);

  const pyBlock = generatePythonContractBlock(contract);

  updatePythonFile(GMN_GYM_PATH, pyBlock);
  updatePythonFile(GMN_PETTINGZOO_PATH, pyBlock);
  updatePythonFile(CHECKPOINT_CONTRACT_PY_PATH, pyBlock);

  console.log('==================================================');
  console.log('✓ All contract targets successfully synchronized!');
  console.log('==================================================');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  syncContracts();
}
